### ISSUE TITLE
Starter project for React throws: "Error: Cannot find module 'fuse-box'"

### ISSUE THREAD

**Issue by stijnvanlieshout** [fuse-box/fuse-box#1009]
I used the starter project for React a while ago (v2.2.3) and it worked fine. The update to v3 causes the following error after running npm install and then node fuse.js:

```
module.js:544
    throw err;
    ^

Error: Cannot find module 'fuse-box'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Stijnvanlieshout/react-mui/fuse.js:1:152)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```
Any idea how to resolve this error?

**Comment by nchanged** [comment]
Make sure you have fuse-box 3.0.2 installed (patched)

**Comment by nchanged** [comment]
Or sorry 3.0.3

**Comment by stijnvanlieshout** [comment]
Of course... solved it. Thanks for the quick reply.

**Comment by nchanged** [comment]
np problem ;-)
