### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by Yuan-Far** [fuse-box/fuse-box#1027]
when I used `ts-node fuse.ts`

```
/Users/admin/callMe/node_modules/fuse-box/Utils.js:68
function uglify(contents, { es6 = false, ...opts } = {}) {
                                         ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/admin/callMe/node_modules/fuse-box/CacheBreaker.js:5:17)
```

**Comment by nchanged** [comment]
# Requirements

FuseBox will work on node.js 8.2+ because of async await usage. It's better to take the advantage of the latest features - its much faster than polyfill. If you are unable to upgrade your servers for some reason - no worries, we now have es6 dist for you.

import { FuseBox } from "fuse-box/es6"

**Comment by Yuan-Far** [comment]
thanks, it`s running
