### ISSUE TITLE
UglifyESPlugin crashes when using uglify-es 3.3.8

### ISSUE THREAD

**Issue by kasugaiasuka** [fuse-box/fuse-box#1057]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined
    at Function.byteLength (buffer.js:510:11)
    at UglifyESPluginClass.postBundle (/foo/bar/node_modules/fuse-box/plugins/UglifyESPlugin.js:29:28)
    at plugins.forEach.plugin (/foo/bar/node_modules/fuse-box/core/WorkflowContext.js:424:34)
    at Array.forEach (<anonymous>)
    at WorkFlowContext.triggerPluginsMethodOnce (/foo/bar/node_modules/fuse-box/core/WorkflowContext.js:409:22)
    at FuseBox.triggerPost (/foo/bar/node_modules/fuse-box/core/FuseBox.js:170:22)
    at realm_utils_1.chain.then.result (/foo/bar/node_modules/fuse-box/core/FuseBox.js:275:22)
    at <anonymous>
```

If 3.3.7 is specified, everything works correctly.
I think 3.3.8 might have some breaking changes...

Node 9.4.0
FuseBox 3.0.2

**Comment by nchanged** [comment]
Hi @kasugaiasuka 
Could you investigate what's exactly broken?

**Comment by kasugaiasuka** [comment]
> what's exactly broken?

My attention.
I attached debugger to uglify-es and found that "unsafe_Func" options was renamed to "unsafe_Function".
Sorry to bother you.
