### ISSUE TITLE
CSSResourcePlugin crashes with "TypeError: Cannot read property 'startsWith' of undefined"

### ISSUE THREAD

**Issue by robertkruis** [fuse-box/fuse-box#1084]
When the CSSResourcePlugin runs into a data URL, the plugin crashes with the error mentioned in the title.
This is due to the fact that the `CSSUrlParser.extractValue()` will return undefined when a data URL is encountered. This will in turn crash the `contents.replace()` call in the `CSSUrlParser.walk()` method.

The stacktrace is as follows:

> TypeError: Cannot read property 'startsWith' of undefined
    at walker (D:\Project_Lucom\Project_Template_LIP\trunk\lipbase\external-scripts\forms\Thinktank\client\node_modules\.registry.npmjs.org\fuse-box\3.1.0-next.20\node_modules\fuse-box\plugins\stylesheet\CSSResourcePlugin.js:105:21)
    at contents.replace (D:\Project_Lucom\Project_Template_LIP\trunk\lipbase\external-scripts\forms\Thinktank\client\node_modules\.registry.npmjs.org\fuse-box\3.1.0-next.20\node_modules\fuse-box\lib\CSSUrlParser.js:29:30)
    at String.replace (<anonymous>)
    at Function.walk (D:\Project_Lucom\Project_Template_LIP\trunk\lipbase\external-scripts\forms\Thinktank\client\node_modules\.registry.npmjs.org\fuse-box\3.1.0-next.20\node_modules\fuse-box\lib\CSSUrlParser.js:22:25)
    at CSSResourcePluginClass.transform (D:\Project_Lucom\Project_Template_LIP\trunk\lipbase\external-scripts\forms\Thinktank\client\node_modules\.registry.npmjs.org\fuse-box\3.1.0-next.20\node_modules\fuse-box\plugins\stylesheet\CSSResourcePlugin.js:161:53)
    at tasks.push (D:\Project_Lucom\Project_Template_LIP\trunk\lipbase\external-scripts\forms\Thinktank\client\node_modules\.registry.npmjs.org\fuse-box\3.1.0-next.20\node_modules\fuse-box\core\File.js:162:63)
    at realm_utils_1.each.promise (D:\Project_Lucom\Project_Template_LIP\trunk\lipbase\external-scripts\forms\Thinktank\client\node_modules\.registry.npmjs.org\fuse-box\3.1.0-next.20\node_modules\fuse-box\core\File.js:173:66)
    at iterate (D:\Project_Lucom\Project_Template_LIP\trunk\lipbase\external-scripts\forms\Thinktank\client\node_modules\.registry.npmjs.org\realm-utils\1.0.9\node_modules\realm-utils\dist\commonjs\each.js:79:34)
    at D:\Project_Lucom\Project_Template_LIP\trunk\lipbase\external-scripts\forms\Thinktank\client\node_modules\.registry.npmjs.org\realm-utils\1.0.9\node_modules\realm-utils\dist\commonjs\each.js:83:29
    at <anonymous>

**Comment by robertkruis** [comment]
@nchanged I provided a PR with a fix for this issue
