### ISSUE TITLE
SassPlugin Non-Boolean Importer Not Working

### ISSUE THREAD

**Issue by JohnLouderback** [fuse-box/fuse-box#1094]
Per the documentation, The SassPlugin accepts a few options (such as `importer: true`) and also accept node sass options. Node sass has an option `importer` that accepts a importer function. I'm attempting to use `node-sass-json-importer` to allow me to import json files as variables. However, when build I get this following stack trace (full paths removed for brevity):

```
TypeError: Cannot read property 'includePaths' of undefined
    at Object.exports.default [as importer] (node_modules\node-sass-json-importer\dist\no
de-sass-json-importer.js:36:35)
    at CSSDependencyExtractor.getPath (node_modules\fuse-box\lib\CSSDependencyExtractor.j
s:47:34)
    at CSSDependencyExtractor.findTarget (node_modules\fuse-box\lib\CSSDependencyExtracto
r.js:76:37)
    at CSSDependencyExtractor.extractDepsFromString (node_modules\fuse-box\lib\CSSDepende
ncyExtractor.js:15:31)
    at new CSSDependencyExtractor (node_modules\fuse-box\lib\CSSDependencyExtractor.js:9:
14)
    at Function.init (node_modules\fuse-box\lib\CSSDependencyExtractor.js:86:16)
    at WorkFlowContext.extractCSSDependencies (node_modules\fuse-box\core\WorkflowContext
.js:286:75)
    at SassPluginClass.transform (node_modules\fuse-box\plugins\stylesheet\SassPlugin.js:
67:46)
    at tasks.push (node_modules\fuse-box\core\File.js:162:63)
    at realm_utils_1.each.promise (node_modules\fuse-box\core\File.js:173:66)
TypeError: Cannot read property 'includePaths' of undefined
    at Object.exports.default [as importer] (node_modules\node-sass-json-importer\dist\no
de-sass-json-importer.js:36:35)
    at CSSDependencyExtractor.getPath (node_modules\fuse-box\lib\CSSDependencyExtractor.j
s:47:34)
    at CSSDependencyExtractor.findTarget (node_modules\fuse-box\lib\CSSDependencyExtracto
r.js:76:37)
    at CSSDependencyExtractor.extractDepsFromString (node_modules\fuse-box\lib\CSSDepende
ncyExtractor.js:15:31)
    at new CSSDependencyExtractor (node_modules\fuse-box\lib\CSSDependencyExtractor.js:9:
14)
    at Function.init (node_modules\fuse-box\lib\CSSDependencyExtractor.js:86:16)
    at WorkFlowContext.extractCSSDependencies (node_modules\fuse-box\core\WorkflowContext
.js:286:75)
    at SassPluginClass.transform (node_modules\fuse-box\plugins\stylesheet\SassPlugin.js:67:46)
    at tasks.push (node_modules\fuse-box\core\File.js:162:63)
    at realm_utils_1.each.promise (node_modules\fuse-box\core\File.js:173:66)

```

**Comment by nchanged** [comment]
@JohnLouderback could you share a config sample that is supposed to be working?

**Comment by JohnLouderback** [comment]
```js
const {
  FuseBox,
  VueComponentPlugin,
  QuantumPlugin,
  HTMLPlugin,
  SassPlugin,
  CSSPlugin,
  CSSResourcePlugin,
  WebIndexPlugin,
  Sparky,
  EnvPlugin,
  StylusPlugin
} = require('fuse-box');
const jsonImporter = require('node-sass-json-importer');

let fuse;
let isProduction = false;
let fuseConfig = function(isServer = false) {
  const isClient = !isServer;
  const clientPlugins = isClient ? [
    WebIndexPlugin({
      path: './js/built/',
      template: './src/index.html'
    })
  ] : [
      EnvPlugin({ VUE_ENV: "server" })
  ];

  return FuseBox.init({
    tsConfig : './tsconfig.json',
    package: 'default',
    target: isClient ? 'browser@es5' : 'server@es6',
    homeDir: './src',
    output: 'wwwroot/js/built/$name.js',
    //hash: isProduction,
    sourceMaps: !isProduction,
    useTypescriptCompiler: true,
    polyfillNonStandardDefaultUsage: true,
    plugins: [
      VueComponentPlugin({
        style: [
          SassPlugin({
            importer: true
          }),
          CSSResourcePlugin(),
          CSSPlugin({
            group: 'components.css',
            inject: (file) => `css/${file}`,
            outFile: 'wwwroot/css/components.css'
          })
        ]
      }),
      [
        StylusPlugin(),
        CSSResourcePlugin(),
        CSSPlugin({
          group: 'theme.css',
          inject: (file) => `css/${file}`,
          outFile: 'wwwroot/css/theme.css'
        })
      ],
      [
        SassPlugin({
          importer: jsonImporter
        }),
        CSSResourcePlugin(),
        CSSPlugin({
          group: 'base.css',
          inject: (file) => `css/${file}`,
          outFile: 'wwwroot/css/base.css'
        })
      ],
      ...clientPlugins,
      isProduction && QuantumPlugin({
        bakeApiIntoBundle: 'vendor',
        uglify: true,
        treeshake: true
      }),
    ]
  });
}

Sparky.task('set-prod', () => {
  isProduction = true;
});
Sparky.task('clean', () => Sparky.src('./wwwroot/js/built')
  .clean('./wwwroot/js/built')
  .clean('./wwwroot/css')
  .clean('./wwwroot/assets'));
Sparky.task('watch-assets', () => Sparky.watch('./assets', { base: './src' }).dest('./wwwroot'));
Sparky.task('copy-assets', () => Sparky.src('./assets', { base: './src' }).dest('./wwwroot'));

Sparky.task('config', () => {
  fuseClient = fuseConfig(false);
  fuseServer = fuseConfig(true);

  if (!isProduction) {
    fuseClient.dev({
      open: false,
      proxy: {
        '**': {
          target: 'http://localhost:64333/',
          changeOrigin: true
        }
      }
    });
  }

  const vendor = fuseClient.bundle('vendor').instructions('~ client.ts');

  const clientApp = fuseClient.bundle('client').instructions('> [client.ts]');
  const serverApp = fuseServer.bundle('server').globals({ "default": "*" }).instructions('> server.ts +fuse-box-css');

  if (!isProduction) {
    clientApp.watch().hmr();
    serverApp.watch();
  }
})

Sparky.task('default', ['clean', 'watch-assets', 'config'], () => {
  fuseServer.run();
  return fuseClient.run();
});

Sparky.task('dist', ['clean', 'copy-assets', 'set-prod', 'config'], () => {
  fuseServer.run();
  return fuseClient.run();
});
```

**Comment by nchanged** [comment]
It's quite interesting, but the options are passed as is

It's only being checked for `true` here
https://github.com/fuse-box/fuse-box/blob/8f34f46f7fe0bee771e720d37915749c952b1f86/src/plugins/stylesheet/SassPlugin.ts#L78-L81

**Comment by nchanged** [comment]
Just realised that the problem might be in that JSON importer. Could you reproduce the error in a repository? It would be nice to have a minimum config setup.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
