### ISSUE TITLE
UglifyJS plugin stumbles at assets/libs/fusebox-hot-reload

### ISSUE THREAD

**Issue by unlight** [fuse-box/fuse-box#112]
**fuse-box: 1.3.108**
```
module.exports = {
    connect: (port) => { // <-- Unexpected token operator (>)

        if (FuseBox.isServer) {
            return;
        }
...
```
Looks like uglify do not like ES6 and arrow functions.

```
Error
    at new JS_Parse_Error (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1547:18)
    at js_error (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1555:11)
    at croak (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2094:9)
    at token_error (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2102:9)
    at unexpected (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2109:9)
    at semicolon (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2129:56)
    at simple_statement (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2320:73)
    at eval (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2189:19)
    at eval (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2142:24)
    at block_ (eval at <anonymous> (D:\My\Dev\angular2-blank-project\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2435:20)
```

**Comment by unlight** [comment]
Sorry, probably this is not a source of problem, need additional investigation...

**Comment by nchanged** [comment]
@unlight don't minify dev bundles =) these are only for development=)

**Comment by unlight** [comment]
I understand that, but task such as `gulp serve --prod` is common case in our work.

**Comment by nchanged** [comment]
Fair enough, I will pipe it though babel!

**Comment by unlight** [comment]
`fusebox-websocket` and `fusebox-hot-reload` must be transpiled.
But I think I can handle this issue by myself by doing build and launching simple static server.
