### ISSUE TITLE
Exception while closing bundle when watching for changes

### ISSUE THREAD

**Issue by samppis** [fuse-box/fuse-box#1157]
I'm running fusebox 3.1.3 and having an issue causing the app to crash every time I save a file.

```
Exception while closing bundle server.
FuseProcess.js:44
Error: listen EADDRINUSE :::3000
util.js:1022
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (<app_dir>\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> <app_dir>\src\index.ts:9:5)
    at d (<app_dir>\dist\server.js:57:3565)
    at Function.r.import (<app_dir>\dist\server.js:57:4092)
    at v (<app_dir>\dist\server.js:54:15)
```

**This only happens when:**

- .watch() is used
- the close-function is provided (see below)

I want to use watch for convenience and the close-function is required for debugging to work.

**Steps to reproduce:**

1. I use sparky to run the app with the following configuration
```
context(class {
    getConfig() {
        return FuseBox.init({
            homeDir: "src",
            output: "dist/$name.js",
            target : `server@esnext`,
            sourceMaps: { inline: false, vendor: false },
            plugins: [
                HTMLPlugin()
            ]
        });
    }
})

task("default", async context => {
    const fuse = context.getConfig();
    fuse.dev({ port: 4445, httpServer: false });
    fuse.bundle("server")
        .watch()
        .instructions("> [index.ts]")
        .completed((proc) => {        
            proc.require({
                // To enable debugging (using VS Code)
                close: ({ FuseBox }) => FuseBox.import(FuseBox.mainFile).shutdown()
            });
        });

    await fuse.run();
});
```

2. Run `node ./fuse.js`

3. Save any file like the `index.ts`

Any help is highly appreciated!

**Comment by nchanged** [comment]
Hi,
It’s clear that your application isn’t shut down and the port isn’t released. You need to kill the actual server with process.exit()

**Comment by samppis** [comment]
Thanks for the tip @nchanged! I'm still figuring out where `process.exit()` should be placed so that the server will still get restarted after a file change is detected?

**Comment by nchanged** [comment]
Cant you just use proc.restart() instead?

**Comment by samppis** [comment]
Can't get that working either :/ I'm still a bit puzzled since [this example in the docs](https://fuse-box.org/page/debugging-with-vscode#server-debugging) is using `watch()`. So, not sure if the docs should be updated or if there's something else causing the problem on my end.

**Comment by devmondo** [comment]
@samppis  restart your machine, this is the only way it worked for me as of now. and maybe it won't work.
if you are on windows you can use this small cool utility to kill app by port
https://www.nirsoft.net/utils/cports.html

hope it helps.

**Comment by nchanged** [comment]
Closing this issue due to inactivity.
