### ISSUE TITLE
Error: You need TypeScript installed to transpile modules automatically

### ISSUE THREAD

**Issue by jezikk** [fuse-box/fuse-box#1173]
Hi,

I'm getting the following error during compilation:
```
Error: You need TypeScript installed to transpile modules automatically
    at WorkFlowContext.fatal (C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\fuse-box\core\WorkflowContext.js:207:15)
    at File.transpileUsingTypescript (C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\fuse-box\core\File.js:406:26)
    at File.handleTypescript (C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\fuse-box\core\File.js:435:27)
    at File.consume (C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\fuse-box\core\File.js:261:25)
    at ModuleCollection.resolve (C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\fuse-box\core\ModuleCollection.js:186:24)
    at realm_utils_1.each (C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\fuse-box\core\ModuleCollection.js:78:29)
    at iterateMap (C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\realm-utils\dist\commonjs\each.js:43:34)
    at C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\realm-utils\dist\commonjs\each.js:59:17
    at C:\Users\Michal\Documents\Projects\fusebox-antd-starter\node_modules\realm-utils\dist\commonjs\each.js:63:14
    at new Promise (<anonymous>)
```

tsconfig.json:
```
{
    "compilerOptions": {
        "target": "ES6",
        "sourceMap": true,
        "jsx": "react",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true
    }
}
```

config:
```
homeDir: 'src',
                target: 'browser@es6',
                output: 'dist/$name.js',
                sourceMaps: !this.isProduction,
                cache: !this.isProduction,
                allowSyntheticDefaultImports: true,
                useJsNext: ['antd'],
                alias: {
                    '~/component-indexof.js': 'component-indexof'
                },
```

package.json
```
"dependencies": {
        "antd": "^3.3.1",
        "react": "^16.2.0",
        "react-dom": "^16.2.0"
    },
    "devDependencies": {
        "@types/react": "^16.0.40",
        "@types/react-dom": "^16.0.4",
        "fuse-box": "^3.1.3",
        "less": "^3.0.1",
        "typescript": "^2.7.2",
        "uglify-es": "^3.3.9",
        "uglify-js": "^3.3.16"
    }
```
It's weird because typescript package is already installed. I do not know if it is a bug or wrong configuration.

Thanks,
M.

**Comment by nchanged** [comment]
please install the latest next version; it should be fixed there

**Comment by nchanged** [comment]
@gludion `fuse-box@next`
