### ISSUE TITLE
Node 6.3.1 + fuse-box/es6 = breaks

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1231]
Fuse-box breaks on node 6.3.1 when require('fuse-box/es6') is specified.
```
 custom = util.inspect.defaultOptions.customInspect
                                      ^

TypeError: Cannot read property 'customInspect' of undefined
    at Object.<anonymous> (/Users/joshua/Projects/plantguard/client/node_modules/fliplog/modules/inspector-gadget/index.js:9:39)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/joshua/Projects/plantguard/client/node_modules/fliplog/plugins/inspect.js:1:75)
    at Module._compile (module.js:541:32)
```

**Comment by troynt** [comment]
Hello, FuseBox requires at least Node 8 to run.

See https://github.com/fuse-box/fuse-box/blob/master/package.json#L22

**Comment by jpike88** [comment]
The site currently nothing about a hard minimum version. It's probably worth making that clearer.

![screen shot 2018-04-28 at 8 28 45 pm](https://user-images.githubusercontent.com/9585787/39397026-c6585318-4b22-11e8-93d4-0419db0c552c.png)

**Comment by lighth7015** [comment]
It doesn't run with node 10.4.1, either.

**Comment by nchanged** [comment]
@lighth7015 what's the problem?

**Comment by nchanged** [comment]
Closing this for now. I am on node 10, it's all good. Please re-open the issue elsewise.
