### ISSUE TITLE
TypeError: Cannot read property '_' of undefined

### ISSUE THREAD

**Issue by siddhantgoel** [fuse-box/fuse-box#1241]
I'm trying to run fuse-box on the first example in the documentation but run into the following exception -

```
TypeError: Cannot read property '_' of undefined
    at extractParams (/tmp/box/node_modules/fuse-box/cli/entry.js:8:30)
    at initCLI (/tmp/box/node_modules/fuse-box/cli/entry.js:17:18)
    at Object.<anonymous> (/tmp/box/node_modules/fuse-box/cli/entry.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
```

Here's what the `fuse.js` looks like -

```
const { FuseBox, WebIndexPlugin } = require("fuse-box");
const fuse = FuseBox.init({
    homeDir : "src",
    target : 'browser@es6',
    output : "dist/$name.js",
    plugins : [
        WebIndexPlugin()
    ]
})
fuse.dev(); // launch http server
fuse.bundle("app").instructions(" > app.js").hmr().watch()
fuse.run();
```

The "source code" only has a single `src` folder with an `app.js` file containing a `console.log("hello world")` and nothing else.

Here's what `package.json` looks like

```
{
  "name": "box",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "fuse-box": "^3.2.2",
    "typescript": "^2.8.3",
    "uglify-es": "^3.3.9",
    "uglify-js": "^3.3.23"
  }
}
```

It's pretty much a copy paste from the documentation, so I'm wondering if there's anything extra I need to do to get it running? Fusebox looks like a very promising alternative to webpack so it would be cool if this could be resolved. Thanks!

**Comment by nchanged** [comment]
It looks like you are using fusebox as a CLI command. Please don't do it. 
https://github.com/fuse-box/react-example

```
node fuse
```

**Comment by siddhantgoel** [comment]
That was an easy fix. Thanks!
