### ISSUE TITLE
Property 'transform' of undefined when building

### ISSUE THREAD

**Issue by giraffescarf** [fuse-box/fuse-box#1353]
First of all, thanks for this amazing bundler, it has been working wonderfully so far, but I've encountered this issue whenever I start the building process now.

`TypeError: Cannot read property 'transform' of undefined
    at realm_utils_1.each (/home/node_modules/fuse-box/plugins/vue/VuePlugin.js:203:39)
    at iterate (/home/node_modules/realm-utils/dist/commonjs/each.js:79:34)
    at /home/node_modules/realm-utils/dist/commonjs/each.js:92:16
    at new Promise (<anonymous>)
    at Object.exports.Each [as each] (/home/node_modules/realm-utils/dist/commonjs/each.js:9:12)
    at VueComponentClass.transform (/home/node_modules/fuse-box/plugins/vue/VuePlugin.js:190:52)
    at tasks.push (/home/node_modules/fuse-box/core/File.js:169:59)
    at realm_utils_1.each.promise (/home/node_modules/fuse-box/core/File.js:173:66)
    at iterate (/home/node_modules/realm-utils/dist/commonjs/each.js:79:34)
    at /home/node_modules/realm-utils/dist/commonjs/each.js:92:16`

If I stop the building and start a new one, the error does not appear. My knowledge is far from being good enough to solve this myself.

I'm running Fusebox 3.4.0 and Vue 2.5.16, this never happened using release 3.2.0, if it helps in any way.

Thank you.

**Comment by nchanged** [comment]
hi @giraffescarf I am glad to hear that ;-)

If you can't debug it yourself, it would be nice if you could reproduce it in a separate repository. I can't fix it blindly, the error isn't obvious.

**Comment by giraffescarf** [comment]
Thanks for answering, and sure, give me some time to fix something up.

**Comment by nchanged** [comment]
@giraffescarf got it. I think you need to add CSSPlugin in order to make it work. That's why there is an error.

**Comment by nchanged** [comment]
Yep, you just used it incorrectly. (It's all should be in the doc)
```
style    : [

					StylusPlugin({ importer: true }),
					PostCSSPlugin([autoprefixer({ browsers: ['last 4 versions']})]),
					CSSPlugin()
				]
```

**Comment by giraffescarf** [comment]
Silly mistake from me, works like a charm now. Thank you very much.
