### ISSUE TITLE
Broken bundler

### ISSUE THREAD

**Issue by eddow** [fuse-box/fuse-box#1357]
Just a little bug report as I broke the bundler with a code.
Note, I don't need to run it and it is even buggy, this is not the question. It is just that `fuse-box` threw an unmanaged exception instead of reporting an error.

The code in question is this one
```
import VueType, * as vue, { VueConstructor } from 'vue'
export const Vue: VueConstructor<VueType> = VueType || <any>vue;
```

The exception is this one 
```
TypeError: Cannot read property 'type' of undefined
    at FileAnalysis.nodeIsString (...\node_modules\fuse-box\analysis\FileAnalysis.js:87:21)
    at Function.onNode (...\node_modules\fuse-box\analysis\plugins\ImportDeclaration.js:9:30)
    at traversalPlugins.forEach.plugin (...\node_modules\fuse-box\analysis\FileAnalysis.js:107:89)
    at Array.forEach (<anonymous>)
    at pre (...\node_modules\fuse-box\analysis\FileAnalysis.js:107:64)
    at visit (...\node_modules\fuse-box\ASTTraverse.js:20:23)
    at visit (...\node_modules\fuse-box\ASTTraverse.js:38:25)
    at visit (...\node_modules\fuse-box\ASTTraverse.js:34:29)
    at visit (...\node_modules\fuse-box\ASTTraverse.js:34:29)
    at Function.traverse (...\node_modules\fuse-box\ASTTraverse.js:43:9)
```

**Comment by nchanged** [comment]
Thanks, noted ;-)

**Comment by nchanged** [comment]
```
src/index.ts:1:25 - error TS1005: 'from' expected.

1 import VueType, * as vue, { VueConstructor } from 'vue'
                          ~

src/index.ts:1:46 - error TS1005: ';' expected.

1 import VueType, * as vue, { VueConstructor } from 'vue'
                                               ~~~~

src/index.ts:1:51 - error TS1005: ';' expected.

1 import VueType, * as vue, { VueConstructor } from 'vue'
```

That's invalid syntax. `typescript@next` doesn't allow that. That's not a bug.
