### ISSUE TITLE
[contributing] error related to node ~10 and `gulp dev`

### ISSUE THREAD

**Issue by paxperscientiam** [fuse-box/fuse-box#1446]
This issue pertains to development of `fuse-box` itself.

After cloning the repo and running `yarn` or `npm i` in the repo root, dependencies are installed as. However, `gulp dev` fails when using `node` ~10 with the following error:

```
[00:06:08] Starting 'dev-fuse'...
[00:06:08] 'dev-fuse' errored after 254 ms
[00:06:08] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (/Users/ramos/repos/fuse-box/node_modules/uws/uws.js:40:19)
    at Object.<anonymous> (/Users/ramos/repos/fuse-box/node_modules/uws/uws.js:44:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object._c9fc.s (/Users/ramos/repos/fuse-box/bin/fusebox.js:11:26)
    at Object._c9fc.f.(anonymous function) (/Users/ramos/repos/fuse-box/bin/fusebox.js:4412:21)
    at Object._c9fc.r (/Users/ramos/repos/fuse-box/bin/fusebox.js:27:14)
    at Object._c9fc.f.(anonymous function) (/Users/ramos/repos/fuse-box/bin/fusebox.js:4370:30)
    at Object._c9fc.r (/Users/ramos/repos/fuse-box/bin/fusebox.js:27:14)
    at Object._c9fc.f.(anonymous function) (/Users/ramos/repos/fuse-box/bin/fusebox.js:4019:24)
    at Object._c9fc.r (/Users/ramos/repos/fuse-box/bin/fusebox.js:27:14)
>> FuseBox bundle is ready
>> You can go playground folder 'cd _playground/generic'
>> Start developing `node fuse.js`
```

No idea what this means, but the prevailing wisdom seems to be that downgrading `node` works. Indeed, I downgraded to `node` 9 and all is well.

**Comment by nchanged** [comment]
Do u have node-gyp installed ? I am using node10 without any problems

**Comment by nchanged** [comment]
@paxperscientiam I've just tried it with `v10.14.1` no problems. Something is wrong with your environment. Try re-installing nodejs
