### ISSUE TITLE
Babel7 issue with emotion babel plugin

### ISSUE THREAD

**Issue by bkniffler** [fuse-box/fuse-box#1463]
Hey there,
Here is a minimal example of my issue: https://github.com/bkniffler/fusebox-babel7-issue

Babel7 is now available as a plugin from @eddyw:
https://github.com/fuse-box/fuse-box/pull/1453

There must be a problem with the implementation though. I tried using the emotion babel plugin. While it works great with for example parcel bundler, it will not work with fuse. I included both in the example repository.

Here is the error that appears in console:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.parse (path.js:1431:5)
    at getLabel (/Users/bkniffler/Git/fusebox-babel7/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:177:29)
    at getLabelFromPath (/Users/bkniffler/Git/fusebox-babel7/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:190:10)
    at transformExpressionWithStyles (/Users/bkniffler/Git/fusebox-babel7/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:408:19)
    at transformCssCallExpression (/Users/bkniffler/Git/fusebox-babel7/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:666:31)
    at PluginPass.JSXAttribute (/Users/bkniffler/Git/fusebox-babel7/node_modules/babel-plugin-emotion/dist/babel-plugin-emotion.cjs.dev.js:917:11)
    at newFn (/Users/bkniffler/Git/fusebox-babel7/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/bkniffler/Git/fusebox-babel7/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/bkniffler/Git/fusebox-babel7/node_modules/@babel/traverse/lib/path/context.js:40:17)
```

The problematic line is here: https://github.com/bkniffler/fusebox-babel7-issue/blob/master/src/index.tsx#L57

Removing the box around the line will make the problem disappear (the other box above is not an issue).

**Comment by eddyw** [comment]
Hey there,

Just a hunch, try setting `useTypescriptCompiler` to `false` and check if it works on a minimal example.

I'm currently really busy, so I won't be able to have a closer look at it soon. However, I'll check it out whenever I get some free time.

**Comment by bkniffler** [comment]
Seting the `useTypescriptCompiler` to false doesn't seem to make a difference unfortunately.

**Comment by eddyw** [comment]
I had some time to check it out today and it turns out that there is a library being imported `react-html-attributes` which requires a json file. Add `.plugin(JSONPlugin())` and it works ;)

I haven't checked the library responsible but my guess is that one of (react-)emotion libs or related.

**Comment by eddyw** [comment]
I figured out the issue, the config passed to `transformSync` doesn't include `filename` which is used within the `babel-plugin-emotion` because it's undefined.

I haven't realized it before, but some plugins may use the filename for .. whatever reason. For now, if you set `autoLabel: false`, it works (remove cache first):
```javascript
{
  "presets": [
    "@babel/preset-env",
    [
      "@babel/preset-react"
    ],
    [
      "@emotion/babel-preset-css-prop",
      {
        "autoLabel": false,
        "labelFormat": "[local]",
        "useBuiltIns": false,
        "throwIfNamespace": true
      }
    ]
  ],
  "plugins": [
    "transform-inline-environment-variables"
  ]
}
```
Since it's a port of previous babel plugin, I assume it may have similar issues. I'll make some improvements to it when I get some time.

**Comment by eddyw** [comment]
I opened a PR which should fix this issue.  I added some tests with a helper babel plugin which uses `filename` as well.

I have a project which uses emotion lib and will have a setup with FuseBox and Babel7, so I'll probably have some extra time if improvements are needed.

Btw, PR adds support for `babel.config.js` configuration files as well.

**Comment by bkniffler** [comment]
So cool, I'll close this then. Thanks for all your effort @eddyw
