### ISSUE TITLE
Enabing ensureES5 results in Cannot read property 'rootName' of undefined

### ISSUE THREAD

**Issue by ronnievdc** [fuse-box/fuse-box#1517]
Using the ClassicEditor from ckeditor5 in combination with Fusebox and **ensureES5** enabled breaks the ClassicEditor

Steps to reproduce
```
git clone git@github.com:Owello/fuse-box-ensurees5-bug.git
cd fuse-box-ensurees5-bug
npm ci
node fuse
```
Open a browser and see the error: `Cannot read property 'rootName' of undefined`

In `fuse.js` change to `ensureES5: false` and run `node fuse` again. The error is gone and the editor is shown.

**Comment by nchanged** [comment]
@ronnievdc I wouldn't set ensureES5 on Quantum. Please do it in the `target` field when bundling for production, otherwise use `esnext` for development

**Comment by ronnievdc** [comment]
@nchanged Thanks, i wasn't aware the `target` property also transpiles.

When setting the target a new problem arises
 - When i set `target: "browser"` the generated code still contains `class` which IE11 has not implemented.
 - When i set `target: "browser@es5"` fuse-box crashes with the following error

```
Launching quantum core
  → Generating abstraction, this may take a while
{ SyntaxError: Unexpected token (14154:4)
    at Parser.pp$4.raise (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp$3.parseExprAtom (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:2196:10)
    at Parser.parseExprAtom (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn-jsx/inject.js:399:24)
    at Parser.pp$3.parseExprSubscripts (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:1925:19)
    at Parser.pp$3.parseMaybeConditional (/home/yellenge/Owello/TestCKEditorES5/node_modules/acorn/dist/acorn.js:1956:27)
  pos: 1036533,
  loc: Position { line: 14154, column: 4 },
  raisedAt: 1036534 }
```

When debugging in acron i found the following code:
```javascript
var bt = function (t) { var e; this.value = t, this.dep = new at, this.vmCount = 0, M(t, "__ob__", this), Array.isArray(t) ? (U ? function (e, t, __proto__) {
    if (e === void 0) { e = mt; }
    if (__proto__ === void 0) { __proto__ = e; }
    for (var r = 0, o = n.length; r < o; r++) {
        var i = n[r];
        M(t, i, e[i]);
    }
} : )(t, mt, yt) : , this.observeArray(t); this.walk(t); };
```

Which corresponds to this part of the Vue code
```javascript
/**
   * Observer class that is attached to each observed
   * object. Once attached, the observer converts the target
   * object's property keys into getter/setters that
   * collect dependencies and dispatch updates.
   */
  var Observer = function Observer (value) {
    this.value = value;
    this.dep = new Dep();
    this.vmCount = 0;
    def(value, '__ob__', this);
    if (Array.isArray(value)) {
      if (hasProto) {
        protoAugment(value, arrayMethods);
      } else {
        copyAugment(value, arrayMethods, arrayKeys);
      }
      this.observeArray(value);
    } else {
      this.walk(value);
    }
  };
```

**Comment by nchanged** [comment]
@ronnievdc that's uglify-js error, not `fuse-box`  You should run uglify-js separately with debug mode to identify the issue

**Comment by ronnievdc** [comment]
Thanks for the quick response. After further investigation, it seems to be the output of acorn is correct, but when this output is transpiled by the Typescript compiler the error arises.

I'll get it contact with the Typescript team. Thanks again nchanged. Keep up the good work :-)

Output from acorn
```
var bt = function (t) {
    var e;
    this.value = t, this.dep = new at, this.vmCount = 0, M(t, "__ob__", this), Array.isArray(t) ? (U ? (e = mt, t.__proto__ = e) : function (t, e, n) {
        for (var r = 0, o = n.length; r < o; r++) {
            var i = n[r];
            M(t, i, e[i])
        }
    }(t, mt, yt), this.observeArray(t)) : this.walk(t)
};
```

Output from Typescript
```
var bt = function (t) { var e; this.value = t, this.dep = new at, this.vmCount = 0, M(t, "__ob__", this), Array.isArray(t) ? (U ? function (e, t, __proto__) {
    if (e === void 0) { e = mt; }
    if (__proto__ === void 0) { __proto__ = e; }
    for (var r = 0, o = n.length; r < o; r++) {
        var i = n[r];
        M(t, i, e[i]);
    }
} : )(t, mt, yt) : , this.observeArray(t); this.walk(t); };
```

**Comment by nchanged** [comment]
@ronnievdc no worries ;-) might be. I've submitted a few issues in the past too.

**Comment by ronnievdc** [comment]
Bug submitted: https://github.com/Microsoft/TypeScript/issues/30635
