### ISSUE TITLE
Bundle Size almost double jspm/SystemJS

### ISSUE THREAD

**Issue by tyrsius** [fuse-box/fuse-box#153]
First off: **wow**. The bundle speed of fuse-box is mind-blowing. I have a pretty large app with a lot of dependencies.

Fuse-box bundle
```
Size: 5.7 MB
Time (no cache): 7s 645ms
Time: (warm cache) 1s 607ms
```

jspm/SystemJS's bundle
```
Size: 3.2 MB
Time: 1m 28s 747ms
```

For development work fuse-box's time is a fantastic pain-reliever, but a 78% size increase for production is pretty steep. I'm sure you guys are working on this, but I figured an issue to track with some real numbers wouldn't hurt.

**Comment by devmondo** [comment]
@tyrsius thanks a lot for the kind words :)
yes, Speed and simplicity is our motto :)

regarding size, one of the important facts about FuseBox is that it does not alter your source code, so we really just add the `API` which is 4kb and some few meta data that by no means would increase the size that much.

could you tell us if you are comparing with/without minification? 
are you comparing `JSPM` `bundle` or `build` as the later uses `rollup` for tree shaking thus the size might be smaller.

we are working on `commonjs` tree shaking solution so stay tuned :)

**Comment by nchanged** [comment]
Well each file contains a  commonjs wrapper, once minified it shrinks it down to minimum. have u tried it?

**Comment by tyrsius** [comment]
@devmondo I am using `build`, tree-shaking is at least partially responsible for the size discrepancy.

@nchanged Is minification not the default? The only references to minification I can find in the Fusebox docs are related to css, which I am not using.

**Comment by nchanged** [comment]
@tyrsius no
Imagine each file is having this

```
___scope___.file("hello.vue", function(exports, require, module, __filename, __dirname){ 
```

It mimics the NodeJs environment in your bundle. So after minification it becomes
`s.file("hello.view", e, r, m, f, d)` which cuts down the size drastically.

Your production builds should include [UglifyJsPlugin](http://fuse-box.org/#uglifyjsplugin)

```
plugins: [
    fsbx.UglifyJSPlugin(options)
]
```

I hope that helps and thank you for so such kind words ;-)

**Comment by tyrsius** [comment]
Having trouble getting UglifyJSPlugin working, it's throwing an unlabeled `Error`.

**Comment by nchanged** [comment]
@tyrsius I think you have es6 code there (UglifyJS does not minify es6).
Make sure you have it transpiled to es5 and you run `bundle` and not `devServer` as it adds es6 code (should be fixed btw)

**Comment by tyrsius** [comment]
@nchanged This is the config I am using to bundle

```
let fuseBox = new fuse.FuseBox({
  homeDir: 'client/js/',
  sourceMap: {
    bundleReference: 'sourcemaps.js.map',
    outFile: './build/sourcemaps.js.map'
  },
  outFile: './build/out.js',
  plugins: [
    fuse.BabelPlugin({
      config: {
        sourceMaps: true,
        presets: ['es2015'],
        plugins: [
            ['transform-react-jsx'],
            ['transform-class-properties'],
            ['transform-object-rest-spread']
        ]
      }
    }),
    /\.raw$/, fuse.RawPlugin({extensions: ['.raw', '.md', 'txt']}),
    fuse.UglifyJSPlugin({ outFileName: 'out.min.js' })
  ]
})
fuseBox.bundle('>main.js')
```

**Comment by nchanged** [comment]
Is there a way to debug why UglifyJS throws an error? We need to be absolutely sure that your code is in es5.

**Comment by tyrsius** [comment]
This is the error I get, which comes after fusebox reports that the bundle has been made (Which I assume includes babels transpilation)

```
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)
    at js_error (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)
    at croak (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)
    at token_error (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)
    at expect_token (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2115:9)
    at expect (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2118:36)
    at eval (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2691:13)
    at eval (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)
    at expr_atom (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2621:35)
    at maybe_unary (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)
```

**Comment by nchanged** [comment]
You do have something that kills UglifyJS, for example, I found [this](https://github.com/mishoo/UglifyJS2/issues/348#issuecomment-29186332)

>i found a test case for this: when a return is used outside of a function. try minifying this and you'll get a useless stack trace:
```
if (true) return;
```

**Comment by nchanged** [comment]
May I suggest eslinting your code? For example we just got a [plugin](https://github.com/DoumanAsh/fuse-box-eslint-plugin)

**Comment by tyrsius** [comment]
@nchanged If this gets too deep I can open a seperate issue.

I installed uglify and tried to run it directly and I get a little more info (looks like you guys trim this out)
```
Parse error at build/out.js:103414,14
SyntaxError: Unexpected token punc «(», expected punc «:»
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)
...
```

This is the code in the bundle file at that line, looks like it comes from a fusebox polyfill
```
FuseBox.pkg("tty", {}, function(___scope___){
___scope___.file("index.js", function(exports, require, module, __filename, __dirname){ 

if (FuseBox.isServer) {
    module.exports = global.require("tty");
} else {
    module.exports = {
        isatty() { return false; } // THIS IS THE OFFENDING LINE
    }
}
});
return ___scope___.entry = "index.js";
```

It doesn't seem to like like the function declaration syntax.

If I use the `--acorn` flag on Uglify it gets past this point and errors out here

```
undefined:5028
        self.key.print(output);
                 ^

TypeError: self.key.print is not a function
    at eval (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:5028:18)
    at doit (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:4247:13)
    at AST_Node.eval [as print] (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:4253:13)
    at eval (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:4991:22)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:4985:29)
    at eval (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:4113:19)
    at OutputStream.with_indent (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:4087:38)
    at Object.with_block (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:4112:9)
    at eval (eval at <anonymous> (/Users/tkye/dev/devportal-client/node_modules/uglify-js/tools/node.js:1:0), <anonymous>:4984:48)
```

**Comment by tyrsius** [comment]
@nchanged I ran that linter and nothing printed out, so I assume it passed

**Comment by nchanged** [comment]
@tyrsius thanks a lot!
```
isatty() { return false; } 
```
this seems to be the issue. I will fix it, but not now, going to bed already. It's too risky to make releases when you are tired. What you can do now is [create](http://fuse-box.org/#custom-modules-folder) an override for the shim.

* Add this to your config `modulesFolder: "shims`
* Create a folder `tty`
* Create index.js with the fixed content
* Remove `.fusebox` folder, or set `cache : false`

I hope it will help, and will get you minified ;-)

**Comment by nchanged** [comment]
@tyrsius what's the progress? You can upgrade fusebox to see the changes. Thanks!

**Comment by devmondo** [comment]
@nchanged  `uglyfiyjs` really causing many issues with `fusebox` we need to either use another minifig or  put a recommended `uglifyjs` setting that work with FuseBox

**Comment by tyrsius** [comment]
@nchanged I created the shim. It now runs without erroring, and there is a long time after fusebox gives its bundle report that I think the minifier is running, but there is no output.

**Comment by tyrsius** [comment]
@devmondo @nchanged Do either of you have an example of `UglifyJSPlugin` in use? I have a feeling this is probably user error, but the docs on `UglifyJSPlugin` are empty.

**Comment by nchanged** [comment]
@tyrsius you can upgrade fusebox now. I know if a bundle is huge, it does not really show that it's still in progress. Can try uglifying it directly?

**Comment by tyrsius** [comment]
@nchanged No, nevermind the minifier is working! I was confused because fuse-box still outputs the bundle report before the minifier

```
   Size: 5.7 MB
    Time: 1s 146ms
```

and then the minifier runs with no console output. However, the bundle file is minified, and it is clocking in at 3.5MB, only 200k larger than jspm. The gzipped size is 880k compared to the jspm gzipped size of 834k. This is totally workable. Please consider adding some console output to the UglifyJSPlugin to indicate success and the final bundle size.

**Comment by nchanged** [comment]
Thanks!!!
