### ISSUE TITLE
v4: can't find path on Windows

### ISSUE THREAD

**Issue by tomByrer** [fuse-box/fuse-box#1569]
After reninstall, I get same error.
Windows 10 paths might be issue?

```bash
pnpm install
Lockfile is up-to-date, resolution step is skipped
Packages: +921
...
+ fuse-box 4.0.0-alpha.58

$ node fuse
internal/modules/cjs/loader.js:236
      throw err;
      ^

Error: Cannot find module 'C:\Users\tom\OneDrive\Documents\github\tombyrer\webvtt\youtube-captions-scraper\node_modules\fuse-box\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:228:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:365:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:27)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\tom\OneDrive\Documents\github\tombyrer\webvtt\youtube-captions-scraper\fuse.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\tom\\OneDrive\\Documents\\github\\tombyrer\\webvtt\\youtube-captions-scraper\\node_modules\\fuse-box\\package.json',   
  requestPath: 'fuse-box'
}
```

**Comment by nchanged** [comment]
I think it just can't resolve your modules. Make sure that package is installed. (Never tired with pnpm)

**Comment by nchanged** [comment]
@tomByrer any update on that one?

**Comment by nchanged** [comment]
Please re-open if the issue still present.
