### ISSUE TITLE
v4 won't work with jsx in js files

### ISSUE THREAD

**Issue by dzek69** [fuse-box/fuse-box#1595]
As reported on Gitter: https://gitter.im/fusebox-bundler/Lobby?at=5d6640cba080d70ab594e920

Using JSX inside `*.js` files causes fuse-box to crash with error like:
```
ParseError [SyntaxError]: [11:8]: Unexpected token: '<'
    at report (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:612:13)
    at parsePrimaryExpressionExtended (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:4037:15)
    at parseExpression (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:3472:18)
    at parseArguments (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:4157:25)
    at parseMemberOrUpdateExpression (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:3813:32)
    at parseExpressionOrLabelledStatement (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:2603:14)
    at parseStatement (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:2581:22)
    at parseStatementListItem (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:2531:22)
    at parseModuleItem (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:2502:22)
    at parseModuleItemList (C:\Users\dzek\Projects\react-perfect\node_modules\meriyah\dist\meriyah.umd.js:2489:27) {
  index: 236,
  line: 11,
  column: 8,
  description: "[11:8]: Unexpected token: '<'"
```

**Comment by nchanged** [comment]
Don't you worry, will get fixed today or tomorrow.
