### ISSUE TITLE
Dev mode errors v4

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1672]
Have managed to completly set up fuse v4 to make production bundles, with less and resource bundleling.

Started, using the same config, to work on the dev server. Now:

- less is not calculated (no style is generated), nor are resources bundled

- instead of getting a vendor and app javascript file, I get four files: 055aff90f_app.js, 055aff90f_dev, 055aff90f_entry.js and 055aff90f_vendor.js

- index.html includes a reference to the "__ftl" file that does not exist

- adding the screwIE option makes the build process crash

fusebox setup:
```
let { fusebox, sparky, pluginReplace } = require("fuse-box");
class Context {
    runServer;
    getConfig = (useSourceMap) =>
        fusebox({
            target: "browser",
            homeDir: "ClientApp",
            entry: "boot-client.tsx",
            output: 'wwwroot/$name',
            webIndex: {
                target: "wwwroot",
            },
            tsConfig: 'tsconfig.json',
            cache: true,
            devServer: this.runServer,
            useTypescriptCompiler: true,
            sourceMap: useSourceMap
        });
}
const { task } = sparky<Context>(Context);
task("start:dev", async ctx => {
    ctx.runServer = true;
    const fuse = ctx.getConfig(true);
    await fuse.runDev(
    //screwIE : false
    );
});
task("build:prod", async ctx => {
    ctx.runServer = false;
    const fuse = ctx.getConfig(false);
    await fuse.runProd({
        uglify: true,
	screwIE: false
    });
});
```

generated index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title></title>
    
  </head>
  <body>
    <script type="text/javascript" src="/055aff90f_dev.js"></script>
<script type="text/javascript" src="/055aff90f_vendor.js"></script>
<script type="text/javascript" src="/055aff90f_app.js"></script>
<script type="text/javascript" src="/__ftl"></script>
<script type="text/javascript" src="/055aff90f_entry.js"></script>
  </body>
</html>
```
With this exact same config production mode works properly

**Comment by nchanged** [comment]
You need to be more explicit about "less is not calculated" I am not understanding what you mean. Please show some snippet.

To disable FTL do: `cache : {FTL : false}`

`screwIE` for dev doesn't exist. `runDev` accepts only a callback.

**Comment by bogdandv** [comment]
no css file is generated

**Comment by bogdandv** [comment]
a resources folder containing this file: 53fb37ae.css.map is generated

**Comment by bogdandv** [comment]
Error in vendor: array is not defined

**Comment by nchanged** [comment]
@bogdandv I am not a magician to guess why this array is not defined ;-) It can be 100000  reasons.

**Comment by bogdandv** [comment]
My bad, this is a custom error of ours... What I am really asking is: Why does it work in production mode?

**Comment by nchanged** [comment]
what does what work?

**Comment by bogdandv** [comment]
the code... no error is thrown in production. All works fine

**Comment by nchanged** [comment]
I can't tell you unless I see it ;-)

**Comment by bogdandv** [comment]
redux saga generates this code in vendor (dev mode):
```

function runAllEffect(effects, effectId, cb) {
    var keys = Object.keys(effects);
    if (!keys.length) {
      return cb(__req1__.is.array(effects) ? [] : {});
    }
    var completedCount = 0;
    var completed = void 0;
    var results = {};
    var childCbs = {};
    function checkEffectEnd() {
      if (completedCount === keys.length) {
        completed = true;
        cb(__req1__.is.array(effects) ? array.from(_extends({}, results, {
          length: keys.length
        })) : results);
      }
    }
    keys.forEach(function (key) {
      var chCbAtKey = function chCbAtKey(res, isErr) {
        if (completed) {
          return;
        }
        if (isErr || __req4__.isEnd(res) || res === CHANNEL_END || res === TASK_CANCEL) {
          cb.cancel();
          cb(res, isErr);
        } else {
          results[key] = res;
          completedCount++;
          checkEffectEnd();
        }
      };
      chCbAtKey.cancel = __req1__.noop;
      childCbs[key] = chCbAtKey;
    });
    cb.cancel = function () {
      if (!completed) {
        completed = true;
        keys.forEach(function (key) {
          return childCbs[key].cancel();
        });
      }
    };
    keys.forEach(function (key) {
      return runEffect(effects[key], effectId, key, childCbs[key]);
    });
  }
```

Production mode generates:
```
function runAllEffect(effects, effectId, cb) {
        var keys = Object.keys(effects);
        if (!keys.length) {
            return cb(utils_1.is.array(effects) ? [] : {});
        }
        var completedCount = 0;
        var completed = void 0;
        var results = {};
        var childCbs = {};
        function checkEffectEnd() {
            if (completedCount === keys.length) {
                completed = true;
                cb(utils_1.is.array(effects) ? utils_1.array.from(_extends({}, results, { length: keys.length })) : results);
            }
        }
        keys.forEach(function (key) {
            var chCbAtKey = function chCbAtKey(res, isErr) {
                if (completed) {
                    return;
                }
                if (isErr || channel_1.isEnd(res) || res === exports.CHANNEL_END || res === exports.TASK_CANCEL) {
                    cb.cancel();
                    cb(res, isErr);
                }
                else {
                    results[key] = res;
                    completedCount++;
                    checkEffectEnd();
                }
            };
            chCbAtKey.cancel = utils_1.noop;
            childCbs[key] = chCbAtKey;
        });
        cb.cancel = function () {
            if (!completed) {
                completed = true;
                keys.forEach(function (key) {
                    return childCbs[key].cancel();
                });
            }
        };
        keys.forEach(function (key) {
            return runEffect(effects[key], effectId, key, childCbs[key]);
        });
    }
```
dev mode throws array is not defined,
prod mode works

**Comment by nchanged** [comment]
@bogdandv could you try it with `fuse-box@4.0.0-alpha.229`? But runDev, runProd doesn't work in alpha yet.

If the issue is still there, please reproduce it, there might be a bug in the compiler

**Comment by bogdandv** [comment]
With    fuse-box@4.0.0-alpha.229 a different error is thrown
FATAL  Error while parsing the code

  - at C:\path\ClientApp2\App.tsx
  - SyntaxError: Line 39, column 9: Property or signature expected
    at report (C:\path\node_modules\buntis\dist\buntis.umd.js:4472:21)
    at parseObjectPropertyKey (C:\path\node_modules\buntis\dist\buntis.umd.js:11008:11)
    at parseInterfaceBody (C:\path\node_modules\buntis\dist\buntis.umd.js:11203:29)
    at parseInterfaceDeclaration (C:\path\node_modules\buntis\dist\buntis.umd.js:11067:20)
    at parseInterfaceOrIdentifier (C:\path\node_modules\buntis\dist\buntis.umd.js:11052:14)
    at parseDeclarationList (C:\path\node_modules\buntis\dist\buntis.umd.js:6139:22)
    at parseDeclarations (C:\path\node_modules\buntis\dist\buntis.umd.js:6109:27)
    at parseSource (C:\path\node_modules\buntis\dist\buntis.umd.js:6087:17)
    at Object.parseTSModule (C:\path\node_modules\buntis\dist\buntis.umd.js:11714:14)
    at Module.parse (C:\path\node_modules\fuse-box\core\Module.js:37:35)

This error appears on a command from an inhouse module, that is compiled using a simple typescript compiler.

Note that fuse-box 3.7.1 can run my project in dev mode, while fuse-box 4 @next can run in production mode, so the inhouse module should be correct.

**Comment by nchanged** [comment]
@bogdandv that's good! You have found new bugs there. Could you copy paste the content of App.tsx ?

**Comment by nchanged** [comment]
this should help `4.0.0-next.147`(hopefully)

**Comment by bogdandv** [comment]
Same thing with `4.0.0-next.147`:
dev mode: 

- array is not defined
- no css is generated from the less files

prod mode:
Build successful

**Comment by bogdandv** [comment]
In prod mode this gets generated:
```
// redux-saga/es/internal/utils.js
$fsx.f[52] = function(module, exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];
    for (var key in source) {
        if (Object.prototype.hasOwnProperty.call(source, key)) {
            target[key] = source[key];
        }
    }
} return target; };
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };
exports.sym = function sym(id) {
    return '@@redux-saga/' + id;
};
exports.TASK = exports.sym('TASK');
exports.HELPER = exports.sym('HELPER');
exports.MATCH = exports.sym('MATCH');
exports.CANCEL = exports.sym('CANCEL_PROMISE');
exports.SAGA_ACTION = exports.sym('SAGA_ACTION');
exports.SELF_CANCELLATION = exports.sym('SELF_CANCELLATION');
exports.konst = function konst(v) {
    return function () {
        return v;
    };
};
exports.kTrue = exports.konst(true);
exports.kFalse = exports.konst(false);
exports.noop = function noop() { };
exports.ident = function ident(v) {
    return v;
};
function check(value, predicate, error) {
    if (!predicate(value)) {
        log('error', 'uncaught at check', error);
        throw new Error(error);
    }
}
exports.check = check;
var hasOwnProperty = Object.prototype.hasOwnProperty;
function hasOwn(object, property) {
    return exports.is.notUndef(object) && hasOwnProperty.call(object, property);
}
exports.hasOwn = hasOwn;
exports.is = {
    undef: function undef(v) {
        return v === null || v === undefined;
    },
    notUndef: function notUndef(v) {
        return v !== null && v !== undefined;
    },
    func: function func(f) {
        return typeof f === 'function';
    },
    number: function number(n) {
        return typeof n === 'number';
    },
    string: function string(s) {
        return typeof s === 'string';
    },
    array: Array.isArray,
    object: function object(obj) {
        return obj && !exports.is.array(obj) && (typeof obj === 'undefined' ? 'undefined' : _typeof(obj)) === 'object';
    },
    promise: function promise(p) {
        return p && exports.is.func(p.then);
    },
    iterator: function iterator(it) {
        return it && exports.is.func(it.next) && exports.is.func(it.throw);
    },
    iterable: function iterable(it) {
        return it && exports.is.func(Symbol) ? exports.is.func(it[Symbol.iterator]) : exports.is.array(it);
    },
    task: function task(t) {
        return t && t[exports.TASK];
    },
    observable: function observable(ob) {
        return ob && exports.is.func(ob.subscribe);
    },
    buffer: function buffer(buf) {
        return buf && exports.is.func(buf.isEmpty) && exports.is.func(buf.take) && exports.is.func(buf.put);
    },
    pattern: function pattern(pat) {
        return pat && (exports.is.string(pat) || (typeof pat === 'undefined' ? 'undefined' : _typeof(pat)) === 'symbol' || exports.is.func(pat) || exports.is.array(pat));
    },
    channel: function channel(ch) {
        return ch && exports.is.func(ch.take) && exports.is.func(ch.close);
    },
    helper: function helper(it) {
        return it && it[exports.HELPER];
    },
    stringableFunc: function stringableFunc(f) {
        return exports.is.func(f) && hasOwn(f, 'toString');
    }
};
exports.object = {
    assign: function assign(target, source) {
        for (var i in source) {
            if (hasOwn(source, i)) {
                target[i] = source[i];
            }
        }
    }
};
function remove(array, item) {
    var index = array.indexOf(item);
    if (index >= 0) {
        array.splice(index, 1);
    }
}
exports.remove = remove;
exports.array = {
    from: function from(obj) {
        var arr = Array(obj.length);
        for (var i in obj) {
            if (hasOwn(obj, i)) {
                arr[i] = obj[i];
            }
        }
        return arr;
    }
};
function deferred() {
    var props = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
    var def = _extends({}, props);
    var promise = new Promise(function (resolve, reject) {
        def.resolve = resolve;
        def.reject = reject;
    });
    def.promise = promise;
    return def;
}
exports.deferred = deferred;
function arrayOfDeffered(length) {
    var arr = [];
    for (var i = 0; i < length; i++) {
        arr.push(deferred());
    }
    return arr;
}
exports.arrayOfDeffered = arrayOfDeffered;
function delay(ms) {
    var val = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : true;
    var timeoutId = void 0;
    var promise = new Promise(function (resolve) {
        timeoutId = setTimeout(function () {
            return resolve(val);
        }, ms);
    });
    promise[exports.CANCEL] = function () {
        return clearTimeout(timeoutId);
    };
    return promise;
}
exports.delay = delay;
function createMockTask() {
    var _ref;
    var running = true;
    var _result = void 0, _error = void 0;
    return _ref = {}, _ref[exports.TASK] = true, _ref.isRunning = function isRunning() {
        return running;
    }, _ref.result = function result() {
        return _result;
    }, _ref.error = function error() {
        return _error;
    }, _ref.setRunning = function setRunning(b) {
        return running = b;
    }, _ref.setResult = function setResult(r) {
        return _result = r;
    }, _ref.setError = function setError(e) {
        return _error = e;
    }, _ref;
}
exports.createMockTask = createMockTask;
function autoInc() {
    var seed = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 0;
    return function () {
        return ++seed;
    };
}
exports.autoInc = autoInc;
exports.uid = autoInc();
var kThrow = function kThrow(err) {
    throw err;
};
var kReturn = function kReturn(value) {
    return { value: value, done: true };
};
function makeIterator(next) {
    var thro = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : kThrow;
    var name = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : '';
    var isHelper = arguments[3];
    var iterator = { name: name, next: next, throw: thro, return: kReturn };
    if (isHelper) {
        iterator[exports.HELPER] = true;
    }
    if (typeof Symbol !== 'undefined') {
        iterator[Symbol.iterator] = function () {
            return iterator;
        };
    }
    return iterator;
}
exports.makeIterator = makeIterator;
/**
  Print error in a useful way whether in a browser environment
  (with expandable error stack traces), or in a node.js environment
  (text-only log output)
 **/
function log(level, message) {
    var error = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : '';
    /*eslint-disable no-console*/
    if (typeof window === 'undefined') {
        console.log('redux-saga ' + level + ': ' + message + '\n' + (error && error.stack || error));
    }
    else {
        console[level](message, error);
    }
}
exports.log = log;
function deprecate(fn, deprecationWarning) {
    return function () {
        return fn.apply(undefined, arguments);
    };
}
exports.deprecate = deprecate;
exports.updateIncentive = function updateIncentive(deprecated, preferred) {
    return deprecated + ' has been deprecated in favor of ' + preferred + ', please update your code';
};
exports.internalErr = function internalErr(err) {
    return new Error('\n  redux-saga: Error checking hooks detected an inconsistent state. This is likely a bug\n  in redux-saga code and not yours. Thanks for reporting this in the project\'s github repo.\n  Error: ' + err + '\n');
};
exports.createSetContextWarning = function createSetContextWarning(ctx, props) {
    return (ctx ? ctx + '.' : '') + 'setContext(props): argument ' + props + ' is not a plain object';
};
exports.wrapSagaDispatch = function wrapSagaDispatch(dispatch) {
    return function (action) {
        return dispatch(Object.defineProperty(action, exports.SAGA_ACTION, { value: true }));
    };
};
exports.cloneableGenerator = function cloneableGenerator(generatorFunc) {
    return function () {
        for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
            args[_key] = arguments[_key];
        }
        var history = [];
        var gen = generatorFunc.apply(undefined, args);
        return {
            next: function next(arg) {
                history.push(arg);
                return gen.next(arg);
            },
            clone: function clone() {
                var clonedGen = cloneableGenerator(generatorFunc).apply(undefined, args);
                history.forEach(function (arg) {
                    return clonedGen.next(arg);
                });
                return clonedGen;
            },
            return: function _return(value) {
                return gen.return(value);
            },
            throw: function _throw(exception) {
                return gen.throw(exception);
            }
        };
    };
};
//# sourceMappingURL=utils.js.map
}
```
and then variable utils_1 is defined
`var utils_1 = $fsx.r(52);`
wich then gets used to refference the array function.

Example:
```
function runAllEffect(effects, effectId, cb) {
        var keys = Object.keys(effects);
        if (!keys.length) {
            return cb(utils_1.is.array(effects) ? [] : {});
        }
        var completedCount = 0;
        var completed = void 0;
        var results = {};
        var childCbs = {};
        function checkEffectEnd() {
            if (completedCount === keys.length) {
                completed = true;
                cb(utils_1.is.array(effects) ? utils_1.array.from(_extends({}, results, { length: keys.length })) : results);
            }
        }
        keys.forEach(function (key) {
            var chCbAtKey = function chCbAtKey(res, isErr) {
                if (completed) {
                    return;
                }
                if (isErr || channel_1.isEnd(res) || res === exports.CHANNEL_END || res === exports.TASK_CANCEL) {
                    cb.cancel();
                    cb(res, isErr);
                }
                else {
                    results[key] = res;
                    completedCount++;
                    checkEffectEnd();
                }
            };
            chCbAtKey.cancel = utils_1.noop;
            childCbs[key] = chCbAtKey;
        });
        cb.cancel = function () {
            if (!completed) {
                completed = true;
                keys.forEach(function (key) {
                    return childCbs[key].cancel();
                });
            }
        };
        keys.forEach(function (key) {
            return runEffect(effects[key], effectId, key, childCbs[key]);
        });
    }
```
IN DEV MODE:
```
function runAllEffect(effects, effectId, cb) {
    var keys = Object.keys(effects);
    if (!keys.length) {
      return cb(__req1__.is.array(effects) ? [] : {});
    }
    var completedCount = 0;
    var completed = void 0;
    var results = {};
    var childCbs = {};
    function checkEffectEnd() {
      if (completedCount === keys.length) {
        completed = true;
        cb(__req1__.is.array(effects) ? array.from(_extends({}, results, {
          length: keys.length
        })) : results);
      }
    }
    keys.forEach(function (key) {
      var chCbAtKey = function chCbAtKey(res, isErr) {
        if (completed) {
          return;
        }
        if (isErr || __req4__.isEnd(res) || res === CHANNEL_END || res === TASK_CANCEL) {
          cb.cancel();
          cb(res, isErr);
        } else {
          results[key] = res;
          completedCount++;
          checkEffectEnd();
        }
      };
      chCbAtKey.cancel = __req1__.noop;
      childCbs[key] = chCbAtKey;
    });
    cb.cancel = function () {
      if (!completed) {
        completed = true;
        keys.forEach(function (key) {
          return childCbs[key].cancel();
        });
      }
    };
    keys.forEach(function (key) {
      return runEffect(effects[key], effectId, key, childCbs[key]);
    });
  }
```

**Comment by nchanged** [comment]
Ok, then please reproduce it. And also if you could give me that file that fails in alpha. (the source)

**Comment by SephReed** [comment]
I'm getting a similar error:

```
- SyntaxError: Line 155, column 64: Unexpected
    at report (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:4472:21)
    at parseClassElements (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:8236:11)
    at parseClassMembers (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:7959:21)
    at parseTypescriptClassDeclarationOrExpression (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:7851:20)
    at parseTypescriptClassDeclaration (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:7820:14)
    at parseTypeScriptExportDeclaration (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:6621:25)
    at parseDeclarationList (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:6169:30)
    at parseDeclarations (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:6109:27)
    at parseSource (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:6087:17)
    at Object.parseTSModule (/Users/seph-play/Code/DataViews/Indie-Dev/node_modules/buntis/dist/buntis.umd.js:11751:14)
```

The offending line:
```
...
public isUsingArray(propName?: PropName): propName is number { 
...
```

I tried deleting the `: propName is number` bit, and it compiled.  Then threw an error that `~/Helium-Node/src/index.js ` does not exist (which is true).  It should be pointing to `"local:main": "src/index.ts",` though.

I'm currently trying to upgrade from v3 to v4 within my monorepo.

**Comment by charsleysa** [comment]
@bogdandv @SephReed can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by nchanged** [comment]
This has been fixed and thoroughly tested
