### ISSUE TITLE
4.0 -- tsconfig tsconfig.json was not found. Using internal defaults.SyntaxError

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1684]
using `fuse-box@4.0.0-alpha.256`

```
/test01/:) ts-node ./fuse.ts 

  ⚙  FuseBox 4.0.0-alpha.256
     Mode: development
     Entry: src/index.ts
     Cache: /Users/seph/Code/tmp/test01/node_modules/.fusebox/4.0.0-alpha.256/501e6c24
     FTL reload: enabled

  tsconfig tsconfig.json was not found. Using internal defaults.SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Cache.get (/Users/seph/Code/tmp/test01/node_modules/fuse-box/cache/cache.js:90:39)
    at Cache.restoreModule (/Users/seph/Code/tmp/test01/node_modules/fuse-box/cache/cache.js:254:29)
    at ict.on.props (/Users/seph/Code/tmp/test01/node_modules/fuse-box/main/attach_cache.js:20:19)
    at fns.map.fn (/Users/seph/Code/tmp/test01/node_modules/fuse-box/interceptor/interceptor.js:35:49)
    at Array.map (<anonymous>)
    at Object.sync (/Users/seph/Code/tmp/test01/node_modules/fuse-box/interceptor/interceptor.js:35:39)
    at processModule (/Users/seph/Code/tmp/test01/node_modules/fuse-box/main/assemble.js:151:9)
    at parseDefaultPackage (/Users/seph/Code/tmp/test01/node_modules/fuse-box/main/assemble.js:241:5)
    at Object.assemble (/Users/seph/Code/tmp/test01/node_modules/fuse-box/main/assemble.js:276:5)
```

**Comment by SephReed** [comment]
Erg.  Deleting node_modules/.fusebox fixed it.  Hadn't realized it had been moved.
