### ISSUE TITLE
[V4] fuse-box/cache/cache.js -> Unexpected end of JSON input

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1726]
Example Error for SEO:
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Cache.get (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/cache/cache.js:90:39)
    at Cache.restoreModule (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/cache/cache.js:254:29)
    at ict.on.props (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/main/attach_cache.js:20:19)
    at fns.map.fn (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/interceptor/interceptor.js:35:49)
    at Array.map (<anonymous>)
    at Object.sync (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/interceptor/interceptor.js:35:39)
    at processModule (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/main/assemble.js:147:9)
    at parseDefaultPackage (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/main/assemble.js:227:5)
    at Object.assemble (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/main/assemble.js:262:5)
```

I'm not sure what causes this, but the solution is to delete `/node_modules/.fusebox` and try again.

------

*Important Note*: This has happened to me on my first run of fusebox for every new project I've started with it.

**Comment by charsleysa** [comment]
Closed due to inactivity.
