### ISSUE TITLE
[v4] Clearer error messaging around bad fallback or template paths

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1733]
Code section

https://github.com/fuse-box/fuse-box/blob/master/src/dev-server/devServer.ts#L59-L65

Current error:
```
TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/express/lib/response.js:425:11)
    at app.use (/Users/seph/Code/ChooseHealth/instride-storefront/node_modules/fuse-box/dev-server/devServer.js:44:13)
```

Suggestion:
Putting a try/catch around these lines, and outputting the error as well as the absolute path that was attempted.  Would make it a lot easier to tell what's wrong with the current supplied path.

**Comment by charsleysa** [comment]
Closed due to inactivity.
