### ISSUE TITLE
[v4] HMR not working, am I missing some dependency?

### ISSUE THREAD

**Issue by stijnvanlieshout** [fuse-box/fuse-box#1752]
I'm migrating from v3 to v4. The app works fine on the first load, but when I edit a file, and HMR kicks in, the app breaks.

I have a working dummy project up and running for v4 where HMR does work. I've been comparing that one to my production app, but cannot figure out what makes the latter break on HMR. I hope somebody here can point me somewhere. 

I've included the errors reported by fusebox and chrome below. 

Fusebox provides the following error trace:
```
(node:40522) UnhandledPromiseRejectionWarning: TypeError: this[node.argument.type] is not a function
    at Object.ReturnStatement (/Users/sv/dev/myproject/website/node_modules/astring/dist/astring.js:389:31)
    at Object.BlockStatement (/Users/sv/dev/myproject/website/node_modules/astring/dist/astring.js:258:29)
    at Object.MethodDefinition (/Users/sv/dev/myproject/website/node_modules/astring/dist/astring.js:646:31)
    at Object.BlockStatement (/Users/sv/dev/myproject/website/node_modules/astring/dist/astring.js:258:29)
    at Object.ClassDeclaration (/Users/sv/dev/myproject/website/node_modules/astring/dist/astring.js:510:10)
    at Object.Program (/Users/sv/dev/myproject/website/node_modules/astring/dist/astring.js:225:27)
    at Object.generate (/Users/sv/dev/myproject/website/node_modules/astring/dist/astring.js:1093:29)
    at Object.fastTransform (/Users/sv/dev/myproject/website/node_modules/fuse-box/transform/fastTransform/fastTransform.js:105:28)
    at /Users/sv/dev/myproject/website/node_modules/fuse-box/plugins/core/plugin_js.js:26:56
    at /Users/sv/dev/myproject/website/node_modules/fuse-box/interceptor/interceptor.js:35:49
    at Array.map (<anonymous>)
    at Object.sync (/Users/sv/dev/myproject/website/node_modules/fuse-box/interceptor/interceptor.js:35:39)
    at Object.bundleResolveModule (/Users/sv/dev/myproject/website/node_modules/fuse-box/main/process_plugins.js:6:9)
    at fasterThanLight (/Users/sv/dev/myproject/website/node_modules/fuse-box/FTL/FasterThanLightReload.js:100:27)
    at /Users/sv/dev/myproject/website/node_modules/fuse-box/FTL/FasterThanLightReload.js:114:26
    at /Users/sv/dev/myproject/website/node_modules/fuse-box/interceptor/interceptor.js:35:49
(node:40522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40522) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In chrome I get the error:
```
Uncaught SyntaxError: Cannot use import statement outside a module
    at new Function (<anonymous>)
    at 0304e9538_dev.js:628
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (0304e9538_dev.js:627)
    at EventEmitter.emit (0304e9538_vendor.js:23219)
    at WebSocket.client.onmessage (0304e9538_dev.js:733)
```

**Comment by nchanged** [comment]
Which version of fusebox? If it's `alpha` you need need to disable cache. We're getting it ready, and many things are off. Please, be patient or install `next`

**Comment by stijnvanlieshout** [comment]
sorry forgot to mention that. I’m on fuse-box@4.0.0-next.165

**Comment by nchanged** [comment]
which file are you reloading? js or ts? We're working hard on our own compiler, which should come to `next` next week. It all will be fixed there. Disable cache and try if it works (as a temporary workaround)

**Comment by stijnvanlieshout** [comment]
I'm using js. If I disable caching then HMR does work indeed. That will do for the time bein. Thanks!

**Comment by stijnvanlieshout** [comment]
Hi there, can you give me an indication of when the issues above will be fixed? I'm still in `4.0.0-next.165` but this version is not really working well in my project (no cache +  buggy HMR + `fuse.runprod` issues). 

Might it be a better idea to switch back to 3.7 for the time being?

**Comment by nchanged** [comment]
@stijnvanlieshout if it doesn't require much effort and the current next is bugging you - it might be better. We're working hard on making v4 better

**Comment by stijnvanlieshout** [comment]
I understand, appreciate your time and effort. Hope to get back to v4 soon :)

**Comment by charsleysa** [comment]
@stijnvanlieshout can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by charsleysa** [comment]
Closed as no response received.
