### ISSUE TITLE
[v4] Error building for production 

### ISSUE THREAD

**Issue by rizkyramadhan** [fuse-box/fuse-box#1818]
When i try to build [react-example](https://github.com/fuse-box/react-example) using `yarn dist`, this error happens: 

 [ dist ] Starting

  ⚙  FuseBox 4.0.0-next.165
     Mode: production
     Entry: src/index.tsx

 ```
 source transform react-dom/cjs/react-dom.development.js(node:10460) UnhandledPromiseRejectionWarning: TypeError: node.getThenStatement is not a function
    at setResult (/home/riz/playground/react/node_modules/fuse-box/production/transformation/conditionUnwrapper.js:55:52)
    at onIfStatement (/home/riz/playground/react/node_modules/fuse-box/production/transformation/conditionUnwrapper.js:97:17)
    at /home/riz/playground/react/node_modules/fuse-box/production/transformation/conditionUnwrapper.js:110:13
    at Array.forEach (<anonymous>)
    at Object.conditionUnwrapperProduction (/home/riz/playground/react/node_modules/fuse-box/production/transformation/conditionUnwrapper.js:108:17)
    at Object.performStaticTransformations (/home/riz/playground/react/node_modules/fuse-box/production/transformation/index.js:11:26)
    at staticTransform (/home/riz/playground/react/node_modules/fuse-box/production/stages/preparationStage.js:14:26)
    at /home/riz/playground/react/node_modules/fuse-box/production/stages/preparationStage.js:33:13
    at Array.forEach (<anonymous>)
    at /home/riz/playground/react/node_modules/fuse-box/production/stages/preparationStage.js:29:21
(node:10460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nchanged** [comment]
I believe that's cuz of the ts version. A massive update is coming next week which will resolve this issue

**Comment by JakeHedman** [comment]
Any update on this?

**Comment by nchanged** [comment]
Please use the latest alpha, we are fews bugs away from merging into next

**Comment by charsleysa** [comment]
@rizkyramadhan @JakeHedman can you please confirm if the issue still occurs with `fuse-box@4.0.0-next.400`?
Also see [here for info on major changes](https://github.com/fuse-box/fuse-box/blob/master/docs/changelog-fuse-compiler.md)

**Comment by nchanged** [comment]
this shouldn't happen anymore
