### ISSUE TITLE
4.0.0-next.400: import systax throws error

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1843]
When I try to migrate to the newest version, syntax like:

```
import * as joint from "../../../vendor/rappid";
import Link = joint.dia.Link;
```
throws the following error: 

 FATAL  Error while compiling a module
```

  - C:\restOfLinkThatIsIrrelevant
  - TypeError: Cannot read property 'value' of undefined
    at onTopLevelTraverse (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\compiler\transformers\shared\ImportTransformer.js:21:111)
    at Object.fn (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\compiler\program\transpileModule.js:28:36)
    at Object.TopLevelVisit (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\compiler\Visitor\Visitor.js:120:36)
    at Object.transpileModule (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\compiler\program\transpileModule.js:23:19)
    at Object.transformCommonVisitors (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\compiler\transformer.js:103:23)
    at Object.moduleCompiler (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\threading\compile\moduleCompiler.js:15:38)
    at Object.compile (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\threading\worker_threads\compilerHub.js:12:41)
    at C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\asyncModuleResolver.js:144:37
    at new Promise (anonymous)
    at initModule (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\asyncModuleResolver.js:143:24)
```

here is my config:
```
let { fusebox, sparky, pluginReplace } = require("fuse-box");

class Context {
    runServer;
    getConfig = (useSourceMap, watch) =>
        fusebox({
            target: "browser",
            entry: "ClientApp2/boot-client.tsx",
            webIndex: {
                target: "wwwroot",
            },
			//hmr : { plugin : "src/hmr.ts"},
            tsConfig: 'tsconfig.json',
            cache: true,
            devServer: true,
            useTypescriptCompiler: true,
            sourceMap: useSourceMap,
            watcher: watch,
            dependencies: {
                include: ['tslib'],
            }
        });
}

task("start:dev", async ctx => {
    //start server
    ctx.runServer = true;
    const fuse = ctx.getConfig(true, true);
    await fuse.runDev({
		bundles: {
			distRoot: 'ClientApp2',
			app: { path: 'app.js', publicPath: '/static' },
			vendor: { path: 'vendor.js', publicPath: '/static' },
		}
	});
});
```

Note that in the previous version (pre alpha merge) it worked properly

**Comment by charsleysa** [comment]
@bogdandv can you please create a minimal reproduction?

**Comment by nchanged** [comment]
There is no need in that, I am fixing it :)

**Comment by nchanged** [comment]
Please verify the fix in `fuse-box@4.0.0-next.404` @bogdandv

**Comment by bogdandv** [comment]
Issue is **NOT** solved. If we have 

```
import * as joint from "../../../vendor/rappid";
import Vertices = joint.linkTools.Vertices;

export const CustomVertices = Vertices.extend({
...stuff
});
```
this results...
```
  phase Running WarmupPhase   FATAL  Error during production build

  - TypeError: Cannot read property 'value' of undefined
    at isEligibleImportOrExport (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\production\transformers\WarmupPhase_Import.js:26:91)
    at onTopLevelTraverse (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\production\transformers\WarmupPhase_Import.js:67:25)
    at Object.fn (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\compiler\program\transpileModule.js:28:36)
    at Object.TopLevelVisit (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\compiler\Visitor\Visitor.js:115:36)
    at Object.transpileModule (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\compiler\program\transpileModule.js:23:19)
    at runWarmupPhase (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\production\phases\WarmupPhase.js:20:23)
    at WarmupPhase (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\production\phases\WarmupPhase.js:32:13)
    at Object.start (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\production\engine.js:14:23)
    at Object.bundleProd (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\production\bundleProd.js:8:36)
    at execute (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\core\fusebox.js:26:32)
```

**Comment by nchanged** [comment]
@bogdandv here is a proper fix `fuse-box@4.0.0-next.408`

It should also ignore the parent import statement if that reference is a type.

**Comment by bogdandv** [comment]
Made a workaround for fuse-box@4.0.0-next.407 to be able to start my dev server
In fuse-box@4.0.0-next.408 I get the following error:
```
stuff\boot-client.tsx
  - TypeError: Cannot read property 'type' of undefined
    at Object.init (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\module.js:109:26)
    at initModule (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\asyncModuleResolver.js:101:20)
    at initModule (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\asyncModuleResolver.js:91:39)
    at relativeResolve (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\asyncModuleResolver.js:118:42)
    at Object.onResolve (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\asyncModuleResolver.js:167:59)
    at Object.moduleCompiler (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\threading\compile\moduleCompiler.js:25:61)
    at Object.compile (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\threading\worker_threads\compilerHub.js:12:41)
    at C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\asyncModuleResolver.js:144:37
    at new Promise (anonymous)
    at initModule (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\moduleResolver\asyncModuleResolver.js:143:24)
```

**Comment by nchanged** [comment]
Please tru 408 and of you still have issues please paste a snippet

**Comment by nchanged** [comment]
@bogdandv could you reproduce it?

**Comment by bogdandv** [comment]
This error happens on version fuse-box@4.0.0-next.408 and NOT on version fuse-box@4.0.0-next.407
The error message is vague. Trying to figure out what causes the issue

**Comment by nchanged** [comment]
I think it might be related to caching. But I haven't touched that part in the recent changes

**Comment by bogdandv** [comment]
it was the cache... After cache deletion it works

**Comment by nchanged** [comment]
@bogdandv could be nice to understand how to reproduce this issue ;-)

**Comment by nchanged** [comment]
Anyway, I think we can close this issue. I made a safety check on that line. However, this shouldn't happen. If you are able to reproduce and provide the steps, I'd be happy to fix it.

**Comment by bogdandv** [comment]
I achived my issue by building with fuse vs 400, create a cache, upgraded to vs 407, now it does not work. After I delete the cache, now it works

**Comment by nchanged** [comment]
Clear the cache and upgrade to 409
