### ISSUE TITLE
4.0.0-next.400: Turning devServer off issues

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1846]
Can not run on dev mode if devServer is turned off.
This config:
```
class Context {
    runServer;
    getConfig = (useSourceMap, watch) =>
        fusebox({
            target: "browser",
            entry: "ClientApp2/boot-client.tsx",
            webIndex: {
                target: "wwwroot",
            },
			//hmr : { plugin : "src/hmr.ts"},
            tsConfig: 'tsconfig.json',
            cache: true,
            devServer: false,
            useTypescriptCompiler: true,
            sourceMap: useSourceMap,
            watcher: watch,
            dependencies: {
                include: ['tslib'],
            }
        });
}

task("build:dev", async ctx => {
    //start server
    ctx.runServer = true;
    const fuse = ctx.getConfig(true, false);
    await fuse.runDev();
});

```
Yields this error:
```
(node:18408) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'onClientMessage' of undefined
    at Object.createHMR (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\hmr\hmr.js:109:15)
    at Object.createContext (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\core\context.js:89:15)
    at execute (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\core\fusebox.js:11:31)
    at Object.runDev (C:\Dox\src\Dox.Client.Web\node_modules\fuse-box\core\fusebox.js:37:31)
    at C:\Dox\src\Dox.Client.Web\fuse.ts:52:16
    at step (C:\Dox\src\Dox.Client.Web\fuse.ts:33:23)
    at Object.next (C:\Dox\src\Dox.Client.Web\fuse.ts:14:53)
    at C:\Dox\src\Dox.Client.Web\fuse.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Dox\src\Dox.Client.Web\fuse.ts:4:12)
```

**Comment by nchanged** [comment]
`fuse-box@4.0.0-next.403`

**Comment by bogdandv** [comment]
Problem solved. Thank you!
