### ISSUE TITLE
Error running node bundle

### ISSUE THREAD

**Issue by l4nn1312** [fuse-box/fuse-box#1855]
Howdy! I'm trying to compile this node bundle and the bundle process produces no errors but running the bundle gives:
```
Inferno is in development mode.
/Users/l4nn1312/Projects/santacruzbiga/js/server.js:2984
    throw new TypeError('argument fn must be a function')
    ^

TypeError: argument fn must be a function
    at Function.wrapfunction [as function] (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:2984:11)
    at populateConstructorExports (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:5720:45)
    at Object.<anonymous> (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:5486:1)
    at c (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:15769:3584)
    at b.require (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:15769:3346)
    at Object.<anonymous> (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:11145:21)
    at c (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:15769:3584)
    at b.require (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:15769:3346)
    at Object.<anonymous> (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:10290:17)
    at c (/Users/l4nn1312/Projects/santacruzbiga/js/server.js:15769:3584)
```
The `fuse.ts` file I'm using is
```typescript
import { FuseBox, FuseBoxOptions, Sparky, UglifyESPlugin, SassPlugin, CSSPlugin } from "fuse-box";
import TsTransformClasscat from "ts-transform-classcat";
import TsTransformInferno from "ts-transform-inferno";
let fuseTest: FuseBox;
let fuseClient: FuseBox;
let fuseServer: FuseBox;
const fuseOptions: FuseBoxOptions = {
   homeDir: "ts",
   output: "js/$name.js",
   cache: true,
   sourceMaps: { inline: false, vendor: false },
   transformers: {
      before: [TsTransformClasscat(), TsTransformInferno()]
   },
   plugins: [
   //    UglifyESPlugin({
   //       mangle: {
   //         toplevel: true,
   //         screw_ie8: true,
   //       },
   //     }),
     ],
};
const fuseClientOptions: FuseBoxOptions = {
   ...fuseOptions,
   plugins: [
	  // Setup client-side plugins here
      // CSSPlugin()
      SassPlugin({
         includePaths: [
            "node_modules/bourbon/core"
         ]
        }),
      CSSPlugin()
   ],
};
const fuseServerOptions: FuseBoxOptions = {
   ...fuseOptions
};


// Sparky.task("clean", () => {
//    Sparky.src("js")
//       .clean("js")
//       .exec();
// });
Sparky.task("test", ["&clean", "&config"], () => {
   fuseTest = FuseBox.init(fuseOptions);
   fuseTest.bundle("client/bundle").test("[**/**.test.tsx]", null);
});
Sparky.task("client", () => {
   fuseClient = FuseBox.init(fuseClientOptions);
   fuseClient
      .bundle("client")
      .target("browser@es2015")
      // .watch("client/**")
      // .hmr()
      .instructions("> client/index.tsx");
   fuseClient.run();
});
Sparky.task("server", () => {
   fuseServer = FuseBox.init(fuseServerOptions);
   fuseServer
      .bundle("server")
      .target("server@esnext")
      .instructions("> server/index.tsx");
   fuseServer.run();
});
```

**Comment by charsleysa** [comment]
@l4nn1312 this looks like an issue with v3 of fuse-box which is no longer supported. Please try upgrading to v4 using `fuse-box@next`.

**Comment by l4nn1312** [comment]
Thanks! How do I use sparky tasks with `@next`? It doesn't seem very well documented yet (also I can volunteer to help with docs although I'm not the most skilled in TypeScript).

**Comment by nchanged** [comment]
@l4nn1312 hey, yes v3 is no longer supported. And I am afraid that Inferno cannot be used with v4, since we don't use TypeScript to transpile TypeScript ;-) We use our own compiler. But if you are brave enough I could help you implement a transformer for inferno ;-)

**Comment by l4nn1312** [comment]
I can certainly try? Would it be easier and more wildly helpful for us to do Inferno or Vue.js?

**Comment by nchanged** [comment]
VUE is much more popular, so that def is a much better choice

**Comment by l4nn1312** [comment]
Alright let's go with that. I'd like to use single file components if possible. Also could you demonstrate how to use sparky tasks in 4?

**Comment by nchanged** [comment]
for example [here](https://github.com/fuse-box/fuse-box/blob/master/playground/angular_playground/fuse.ts)

And [here](https://slack.fuse-box.org/) is our slack ;-)
