### ISSUE TITLE
Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by bogdandv** [fuse-box/fuse-box#1875]
I get this during compilation of production mode:
```
  downTranspile node_modules/victory-legend/node_modules/lodash/_nativeCreate.js   FATAL  Error during production build

  - TypeError: Cannot read property 'flags' of undefined
    at getFlowTypeOfReference (node_modules\fuse-box\node_modules\typescript\lib\typescript.js:51938:80)
    at tryGetThisTypeAt (node_modules\fuse-box\node_modules\typescript\lib\typescript.js:53340:32)
    at checkThisExpression (\node_modules\fuse-box\node_modules\typescript\lib\typescript.js:53308:24)
    at checkExpressionWorker (\node_modules\fuse-box\node_modules\typescript\lib\typescript.js:60035:28)
    at checkExpression (\node_modules\fuse-box\node_modules\typescript\lib\typescript.js:59983:38)
    at \node_modules\fuse-box\node_modules\typescript\lib\typescript.js:56071:21
    at Object.forEach (node_modules\fuse-box\node_modules\typescript\lib\typescript.js:317:30)
    at resolveUntypedCall (node_modules\fuse-box\node_modules\typescript\lib\typescript.js:56070:20)
    at resolveCallExpression (node_modules\fuse-box\node_modules\typescript\lib\typescript.js:57133:24)
    at resolveSignature (node_modules\fuse-box\node_modules\typescript\lib\typescript.js:57531:28)
```
please note dev mode compiles succesfully

**Comment by nchanged** [comment]
@bogdandv that's related to typescript, we cannot do anything about it. Either report a bug to TypeScript or remove `buildTarget` from `runProd` (which you shouldn't set unless you're targeting IE11)

**Comment by bogdandv** [comment]
I am targetting ie11 :|

**Comment by nchanged** [comment]
I could suggest changing TS version. That might help. The idea behind v4 is that we don't depend on any project except our own. We **don't** use TypeScript except for the case of transpiling down to IE11 level.

**Comment by bogdandv** [comment]
Fuse-box seems to have a dependency on the newest version of typescript.
Won't it just use that version instead of what I have installed?

**Comment by nchanged** [comment]
@bogdandv you are correct, we'd need to re-visit this.

**Comment by bogdandv** [comment]
add a feature request tag?

**Comment by nchanged** [comment]
@bogdandv there are complications with pnpn in regards to making it optional. But we could discuss that in a different issue.

**Comment by bogdandv** [comment]
After change-ing the typescript version to 3.7.4 it works. Using yarn resolution to give 3.7.4 to fuse-box instead of 3.8.2
Is there any feature present in 3.8.2 and not present in 3.7.4 that is used by fuse?

**Comment by nchanged** [comment]
Nope we use it only for down transpiling
