### ISSUE TITLE
Using typescript 3.8+ private class members cause compilation error

### ISSUE THREAD

**Issue by nigel-gott** [fuse-box/fuse-box#1911]
With the latest fuse-box 4.0.0-next.432 private class members like so:

`
// index.ts
class MyRandomGenerator {
    #aPrivateMember = 1
}
`
Cause an odd error when running fusebox:
```
~/src/fusebox-private-bug$ npx ts-node fuse.ts

  ⚙  FuseBox 4.0.0-next.432
     Mode: development
     Entry: /home/nigel/src/fusebox-private-bug/src/index.ts

  init node_modules/fuse-box/modules/fuse-box-websocket/index.js   FATAL  Error while compiling a module

  - /home/nigel/src/fusebox-private-bug/src/index.ts
  - TypeError: this[node.property.type] is not a function
    at Object.MemberExpression (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:594:37)
    at Object.AssignmentExpression (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:262:29)
    at Object.ExpressionStatement (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:447:39)
    at Object.BlockStatement (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:308:37)
    at Object.MethodDefinition (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:625:35)
    at Object.BlockStatement (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:308:37)
    at Object.ClassDeclaration (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:353:14)
    at Object.Program (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:725:33)
    at Object.generate (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/compiler/generator/generator.js:1037:31)
    at Object.moduleCompiler (/home/nigel/src/fusebox-private-bug/node_modules/fuse-box/threading/compile/moduleCompiler.js:73:45)

```
I've constructed a full minimal working example here https://github.com/nigel-gott/possible-fusebox-private-bug . By removing the # and making the class member no longer private fusebox then works correctly.

Typescript's compiler on it's own works as expected:
`npx tsc --target es2015 src/index.ts` 

Apologies if I am missing something with regards to configuring fusebox, by my understanding it should work out of the box with typescript 3.8+ without any extra configuration?

**Comment by nchanged** [comment]
Hi, I will get to implementing this feature this weekend, just to be clear we are not using typescript to transpile ts nor js code, we have a custom compiler. But the implementation is straightforward

**Comment by rizkyramadhan** [comment]
I stumble this bug with another error message, in my case it is 

```
TypeError: this[statement.type] is not a function
    at Object.BlockStatement
```

when I inspect the `statement` object, it shows this:

```
type: 'TSIndexSignature',
  parameters: [
    {
      type: 'Identifier',
      name: 'key',
      range: [Array],
      loc: [Object],
      typeAnnotation: [Object]
    }
  ],
  range: [ 444, 482 ],
  loc: { start: { line: 15, column: 2 }, end: { line: 15, column: 40 } },
  typeAnnotation: {
    type: 'TSTypeAnnotation',
    loc: { start: [Object], end: [Object] },
    range: [ 457, 481 ],
    typeAnnotation: {
      type: 'TSUnionType',
      types: [Array],
      range: [Array],
      loc: [Object]
    }
  }
}
```

Well, I'm aware that there is no 'TS*' member implemented in `this`, hence the bug.

**Comment by nchanged** [comment]
@rizkyramadhan it should show the file name. Is it related to the private class members?

**Comment by rizkyramadhan** [comment]
Ok, found it. This code is the culprit:

```
export class Rectangle extends FullRectangle {
  [key: string]: number | boolean | any;
}
```

No, I think that because I use [key:string] as index signature, the generated AST for above code contains `TSIndexSignature`  (see my `statement` object above) and that `TSIndexSignature` member is not found in generator methods.

There are no method prefixed with TS in generator methods, so any TS* member that needs to be generated will be failed, in your case are private class members, and in my case index signature.

**Comment by nchanged** [comment]
@rizkyramadhan should be fixed in `4.0.0-next.440`

**Comment by rizkyramadhan** [comment]
I hope you can implement whole TS AST. Let me know if you need help

**Comment by nchanged** [comment]
@rizkyramadhan thanks, yes, I do need help. It's mostly implemented. There are cases like private class members that aren't

Here is the [common](https://github.com/fuse-box/fuse-box/blob/ad711eb677cfb61612721edfc1661250967bb607/src/compiler/transformers/ts/CommonTSfeaturesTransformer.ts) conversion happens. Those are the nodes that are removed.
