### ISSUE TITLE
Class fields in js file leads to an error

### ISSUE THREAD

**Issue by starsolaris** [fuse-box/fuse-box#1932]
fuse-box: "4.0.0-next.439"
Next code in js file
```
class A {
	a = 0;
};
```
or 
```
class A {
	#a = 0;
};
```
produce next error on build:
```
- TypeError: this[statement.type] is not a function
    at Object.BlockStatement (G:\source\git\modules\solid\node_modules\fuse-box\compiler\generator\generator.js:308:37)
    at Object.ClassDeclaration (G:\source\git\modules\solid\node_modules\fuse-box\compiler\generator\generator.js:353:14)
    at Object.Program (G:\source\git\modules\solid\node_modules\fuse-box\compiler\generator\generator.js:725:33)
    at Object.generate (G:\source\git\modules\solid\node_modules\fuse-box\compiler\generator\generator.js:1037:31)
    at Object.moduleCompiler (G:\source\git\modules\solid\node_modules\fuse-box\threading\compile\moduleCompiler.js:73:45)

```

**Comment by nchanged** [comment]
It hasn't been implemented yet

**Comment by jpike88** [comment]
dupe of #1911
