### ISSUE TITLE
Web Index template no longer functional

### ISSUE THREAD

**Issue by SephReed** [fuse-box/fuse-box#1934]
Followed these instructions exactly: https://github.com/fuse-box/fuse-box/blob/master/docs/webIndex.md

>(node:42913) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'original' of undefined
    at fileContents.replace (/Users/seph-play/Code/rCommunity/web-app/node_modules/fuse-box/webIndex/webIndex.js:85:62)
    at String.replace (<anonymous>)
    at Object.generate (/Users/seph-play/Code/rCommunity/web-app/node_modules/fuse-box/webIndex/webIndex.js:74:41)
    at ctx.ict.on (/Users/seph-play/Code/rCommunity/web-app/node_modules/fuse-box/webIndex/webIndex.js:115:50)
    at fns.map.fn (/Users/seph-play/Code/rCommunity/web-app/node_modules/fuse-box/interceptor/interceptor.js:48:49)
    at Array.map (<anonymous>)
    at Object.sync (/Users/seph-play/Code/rCommunity/web-app/node_modules/fuse-box/interceptor/interceptor.js:48:39)
    at Object.exports.createBuild (/Users/seph-play/Code/rCommunity/web-app/node_modules/fuse-box/core/build.js:52:13)
(node:42913) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42913) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SephReed** [comment]
```
                else {
                    ctx.log.warn(`Unable to resolve ${result.original}`);
                    return '';
                }
```

The error message assumes something it shouldn't.  But now I get the error is a bad path.

**Comment by SephReed** [comment]
Commenting out this is what caused the error

```
<!-- <link rel="icon" href="$import('assets/favicon.png')" /> -->
```

**Comment by nchanged** [comment]
@SassNinja could you take a look at this functionality? It should be a few lines of code.

**Comment by erikdao** [comment]
@SassNinja @SephReed Have you found any solution for this problem? It seems that I'm also facing this exact problem.
