### ISSUE TITLE
Shiming stopped working

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#198]
Hi, when I add any shim into my config I receive following error:

```
TypeError: Cannot read property 'acceptFiles' of undefined
    at BundleSource.addFile (/Users/tomi/Github/packages/webpack2-typescript/node_modules/fuse-box/dist/commonjs/BundleSource.js:47:71)
    at files.forEach.f (/Users/tomi/Github/packages/webpack2-typescript/node_modules/fuse-box/dist/commonjs/CollectionSource.js:17:37)
    at Array.forEach (native)
    at resolveFiles.then.files (/Users/tomi/Github/packages/webpack2-typescript/node_modules/fuse-box/dist/commonjs/CollectionSource.js:16:19)
```

Here is my config (when I remove the shim, error disappears). I run this with `gulp louis`;

```js
gulp.task("louis-ui", ['copy-louis-html'], () => {
    fsbx.FuseBox.init({
        homeDir: "src",
        log: false,
        sourceMap: {
            bundleReference: 'louis.js.map',
            outFile: `${devReactFolder}/louis.js.map`
        },
        shim: {
            "crypto": {
                exports: "{ randomBytes: () => crypto.getRandomValues(new global.Uint16Array(1))[0] }"
            }
        },
        plugins: [
            typescriptTransform,
            fsbx.JSONPlugin(),
            fsbx.TypeScriptHelpers(), [
                fsbx.CSSResourcePlugin({
                    resolve: (f) => `/resources/${f}`
                }),
                fsbx.CSSPlugin()
            ],
        ],
        outFile: `${devReactFolder}/louis.js`,
    }).devServer("> client/modules/_stories/index.tsx", {
        httpServer: false,
        port: 5678
    });
});

gulp.task('louis-server', function () {
    if (node) node.kill()

    node = spawn('node', ['src/client/modules/_stories/server.js'], {
        stdio: 'inherit'
    })
    node.on('close', function (code) {
        if (code === 8) {
            gulp.log('Error detected, waiting for changes...');
        }
    });
});

gulp.task("copy-louis-html", () => {
    gulp.src("src/client/modules/_stories/louis.html")
        .pipe(gulp.dest(devReactFolder))
});

gulp.task('louis', ['louis-ui'], function () {
    runSequence(['louis-server']);
});
```

**Comment by nchanged** [comment]
Oops, roger that will fix it and cover

**Comment by nchanged** [comment]
Incredibly sorry for that one to slip through. We need more tests, I will move milestones and release the fix with tests very soon.

**Comment by tomitrescak** [comment]
Hey, don't worry about it. You guys created a piece of software that already made several of my days ;) Have already converted all my project to it ;)
