### ISSUE TITLE
Optional chaining emits undefined when used with a function call

### ISSUE THREAD

**Issue by nspaeth** [fuse-box/fuse-box#1981]
Using code like the following:
```
const text = useField('query')?.input?.value;
```
Results in:
```
const text = (_2_ = (_1_ = undefined('query')) === null || _1_ === void 0 ? void 0 : _1_.input) === null 
```
See that `useField` is being emitted as `undefined` and then called.

**Comment by jsbr** [comment]
Probably related:

```
(parent || anchor.parentNode)?.insertBefore(node, anchor.nextSibling)
```

error:
```
TypeError: Cannot set property 'conditionSteps' of undefined
```
fuse-box@4.0.0

**Comment by remotezygote** [comment]
Is this fixed? I am using latest 4.0.0, and it seems like this is still broken.

Repro (with `react-map-gl` library): https://github.com/remotezygote/optchainbug-example

I'm not sure how to debug further other than to isolate the issue to this library...

**Comment by remotezygote** [comment]
And it traces back to this line of code: https://github.com/visgl/react-map-gl/blob/v7.0.7/src/components/use-control.ts#L21

**Comment by remotezygote** [comment]
And in this codebase, the error traces back here: https://github.com/fuse-box/fuse-box/blob/v4.0.0/src/compiler/transformers/optionalChaining/OptionalChainingTransformer.ts#L275

The error:
```
  compiler Completed node_modules/react-map-gl/dist/esm/components/scale-control.js   FATAL  Error while compiling a module

  - /Users/john/workspaces/optchainbug-example/node_modules/react-map-gl/dist/esm/components/use-control.js
  - TypeError: Cannot set properties of undefined (setting 'conditionSteps')
    at createStatement (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/transformers/optionalChaining/OptionalChainingTransformer.js:229:36)
    at onEach (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/transformers/optionalChaining/OptionalChainingTransformer.js:298:37)
    at fn (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/core/transformModule.js:28:21)
    at visitNode (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/core/nodeVisitor.js:35:9)
    at visitNode (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/core/nodeVisitor.js:49:25)
    at visitNode (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/core/nodeVisitor.js:56:21)
    at visitNode (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/core/nodeVisitor.js:49:25)
    at visitNode (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/core/nodeVisitor.js:56:21)
    at visitNode (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/core/nodeVisitor.js:49:25)
    at visitNode (/Users/john/workspaces/optchainbug-example/node_modules/fuse-box/compiler/core/nodeVisitor.js:56:21)
```

**Comment by remotezygote** [comment]
From a quick look at the code, and not knowing exactly the intent of it all, it looks like this might be erroring because it's the first item in the chain, so no `current` has been set?
