### ISSUE TITLE
Compilation error when using TSExportAssignment

### ISSUE THREAD

**Issue by draoncc** [fuse-box/fuse-box#1990]
Trying to compile a [TSExportAssigment](https://docs.rs/swc_ecma_ast/0.18.1/swc_ecma_ast/struct.TsExportAssignment.html) like `export =` errors with:

```
   FATAL  Error during production build

  - TypeError: this[statement.type] is not a function
    at Object.Program (/home/cino/coding/foxbase/selectorsuite/node_modules/fuse-box/compiler/generator/generator.js:744:29)
    at Object.generate (/home/cino/coding/foxbase/selectorsuite/node_modules/fuse-box/compiler/generator/generator.js:1055:29)
    at Object.moduleCompiler (/home/cino/coding/foxbase/selectorsuite/node_modules/fuse-box/threading/compile/moduleCompiler.js:75:45)
```

logging `statement` gives:

```js
{
  type: 'TSExportAssignment',
  expression: {
    type: 'Identifier',
    name: 'router',
    range: [ 321, 327 ],
    loc: { start: [Object], end: [Object] }
  },
  range: [ 312, 328 ],
  loc: { start: { line: 13, column: 0 }, end: { line: 13, column: 16 } }
}
```

---

Minimal example:

index.ts
```typescript
export = {};
```

fuse.ts
```typescript
import { fusebox } from 'fuse-box';

fusebox({ entry: 'index.ts', target: 'server' }).runProd();
```

package.json
```json
{
  "scripts": {
    "build": "ts-node fuse.ts"
  },
  "dependencies": {
    "fuse-box": "^4.0.0",
    "ts-node": "^9.1.1"
  }
}
```

and run `yarn build`

**Comment by nchanged** [comment]
`4.0.1-next.4`
