### ISSUE TITLE
Fusebox Dependancies Don't Pay Nice Running on (Ubuntu) Vagrant With Windows Host Machine.

### ISSUE THREAD

**Issue by ajm113** [fuse-box/fuse-box#220]
So far this only sprouts up trying to run fusebox on a Vagrant machine instance, but it appears the dependancies that fusebox uses generate random errors. I don't see many people on here using Vagrant + Windows. So perhaps I'm the only one expirencing these issues.

## How To Generate Errors
1. Copy/Paste the code below into _Vagrantfile_.
```

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "fusebox-test"
  config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
end

```

2. Run `$ vagrant up` in Windows commandline.
3. SSH into the VM and install node/git/etc...
4. Git Clone any fusebox examples in SSH where `/var/www` is.
5. Run `$ npm install --no-bin-links`. (Obvously Linux/Windows syms don't play nice.)
6. Run `$ node fuse.js`

Now you should be greeted by error messages like these.
```
02:15:13 : Launching dev server on port 4444
/var/www/react-example/node_modules/regenerator-transform/lib/emit.js:88
  return t.

SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/react-example/node_modules/regenerator-transform/lib/visit.js:13:13)
    at Module._compile (module.js:571:32)
```

```
/var/www/node_modules/postcss/lib/map-generator.js:210
        if (typeof th

SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/node_modules/postcss/lib/lazy-result.js:9:21)
    at Module._compile (module.js:571:32)
```

I assume you could fix this by moving the location of `node_modules` outside of the _shared folder_ scope. I'm still sort of new to npm. So correct me if I'm wrong. I'm just going on based on my expirence with gulp.js.

**Comment by devmondo** [comment]
@ajm113 
we got a new undocumented feature, that allows you to point fuse to a custom location for `node_modules` folder , sometihng like below
```
process.env.PROJECT_NODE_MODULES = `C:/projects/fuse-box-random-tests/node_modules`;
const fsbx = require('fuse-box');
```

could you try it please and tell us if it helps at all :)

**Comment by ajm113** [comment]
Of course! :) If that works, IMO I would try to at least note that somewhere in the docs, since a good chunk of people who are forced to use Windows will more than likely be using Vagrant. ;) I'll update my status as soon as I can test this.

**Comment by ajm113** [comment]
Sorry for the delay. I've attempted to run that line with the react example and receive the following error: 

```
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/react-example/node_modules/proxy-addr/index.js:22:14)
    at Module._compile (module.js:570:32)
```

**Comment by devmondo** [comment]
@ajm113  you need to transpile your code with babel or typescript :)

**Comment by devmondo** [comment]
We will close this now for being inactive. by the way, check the new version 2.0, let us know otherwise :)
