### ISSUE TITLE
Import not working inside fuse.js

### ISSUE THREAD

**Issue by tonimain** [fuse-box/fuse-box#323]
I have setup very minimal setup inside my fuse.js file. Everything is installed via yarn.

```javascript
import fsbx from 'fuse-box';
const FuseBox = fsbx.FuseBox;

const config = {
    homeDir: "src/",
    modulesFolder: "fusebox-assemble-templates",
    plugins: [
        fsbx.TypeScriptHelpers(),
        [fsbx.SassPlugin(), fsbx.CSSPlugin()],
        fsbx.BabelPlugin(),
        hbs(),
        fsbx.HTMLPlugin({ useDefault: true })
    ],
    outFile: "./build/bundle.js",
}

const fuse = FuseBox.init(config);

fuse.devServer('> index.js [**/*.hbs]');
```

But after executing npm start i get the following error:

```
fusebox/fuse.js:1
(function (exports, require, module, __filename, __dirname) { import fsbx from 'fuse-box';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by nchanged** [comment]
Please try that
```
cont {FuseBox, TypeScriptHelpers ...} = require("fuse-box")
```

**Comment by tonimain** [comment]
So okay let's have some fun. If you want to use es6 syntax to import fuse-box from node_modules, you should do the following.

First install babel-cli:
```
yarn add --dev babel-cli
```

or just use npm as your preferred package manager.

Than update your config because es6 synatx is a little bit different than the full-config example inside the docs on (http://fuse-box.org/#full-config)

```javascript
import * as fsbx from 'fuse-box'; //you need to tell import all methods as your object fsbx and don't miss the ;

//define your const, write it with underscore and uppercase due to node guidelines and best practice
const _FUSEBOX = fsbx.FuseBox;

const _CONFIG = {
 ...//your configuration comes here
};

```

*Update your package.json script part to use babel-node:

```
"scripts": {
    "start": "babel-node ./fuse.js"
  },

```

**Comment by nchanged** [comment]
Great!
