### ISSUE TITLE
Mongodb Cannot read property 'ObjectId' of undefined

### ISSUE THREAD

**Issue by squiles** [fuse-box/fuse-box#347]
I'm sure there is something missing here that is plain obvious but somehow I can't get this simple example to work.

My fuse.js file

```javascript
const fsbx = require("fuse-box");

let config = {
    homeDir: "app/",
    sourceMap: {
        bundleReference: "main.js.map",
        outFile: "./build/main.js.map",
    },
    outFile: "./build/main.js",
    log : 'true',
    debug: 'true',

    plugins: [
        fsbx.SVGPlugin(),
        fsbx.CSSPlugin(),
        fsbx.BabelPlugin({
            config: {
                "sourceMaps": true,
                /*"presets": ["es2015", "stage-0"],
                // "presets": ["camo"],1
                "plugins": [
                    "transform-es2015-modules-commonjs"
                ]*/
                "presets": ["es2017", "stage-0"],
                "plugins": [
                    ["transform-decorators-legacy"]
                ]
            }
        })
    ]
};

if (process.env.NODE_ENV === 'serve') {
    new fsbx.FuseBox(config).devServer(">main.js");
}

if (process.env.NODE_ENV === 'production') {
    new fsbx.FuseBox(config).bundle(">main.js");
}
```

My main file

```javascript

import mongoose from 'mongoose';

let databaseHost = 'localhost';
let databaseName = 'workout';

let databaseConnectUri = 'mongodb://' + databaseHost + '/' + databaseName;

mongoose.connect(databaseConnectUri);
```

and the relevant part of my package.json file

```javascript
"dependencies": {
    "babel-core": "^6.20.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-stage-0": "^6.22.0",
    "camo": "^0.12.3",
    "express": "^4.15.0",
    "mongoose": "^4.8.5"
  },
  "devDependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.23.0",
    "babel-preset-es2017": "^6.22.0",
    "fuse-box": "^1.3.122",
    "nodemon": "^1.11.0"
  }
```

I always get the same error: 

```
var ObjectId = require('../drivers').ObjectId;
                                    ^

TypeError: Cannot read property 'ObjectId' of undefined
    at Number.<anonymous> (/Users/joaogomes/workout-server/build/main.js:3961:37)
    at g (/Users/joaogomes/workout-server/build/main.js:31330:3502)
    at w.require (/Users/joaogomes/workout-server/build/main.js:31330:3278)
    at Number.<anonymous> (/Users/joaogomes/workout-server/build/main.js:3061:16)
    at g (/Users/joaogomes/workout-server/build/main.js:31330:3502)
    at w.require (/Users/joaogomes/workout-server/build/main.js:31330:3278)
    at Number.<anonymous> (/Users/joaogomes/workout-server/build/main.js:2092:13)
    at g (/Users/joaogomes/workout-server/build/main.js:31330:3502)
    at w.require (/Users/joaogomes/workout-server/build/main.js:31330:3278)
    at Number.<anonymous> (/Users/joaogomes/workout-server/build/main.js:1571:18)

```

Can someone help me?

**Comment by nchanged** [comment]
Hi, modify your arithmetic instructions - isolate node_modules

```
> [index.ts]
```
I hope that helps

**Comment by squiles** [comment]
You are a real life saver 😄 . I guess I just didn't understand how arithmetic instructions really work. Maybe the documentation on the website could provide more examples or maybe it's just me that didn't get it. Anyway, thanks a lot.

**Comment by nchanged** [comment]
No worries, we will update them :) always welcome!
