### ISSUE TITLE
Cannot bundle a large project

### ISSUE THREAD

**Issue by niieani** [fuse-box/fuse-box#358]
I'm trying to bundle a super large project (currently using Webpack, where the output bundle is around 35 MB), and after configuring FuseBox, I'm getting the following error. Not sure where it's coming from or what's causing it. 

```
TypeError: this[type] is not a function
    at CodeGenerator.generateExpression (/home/me/project/node_modules/escodegen/escodegen.js:2456:28)
    at CodeGenerator.CallExpression (/home/me/project/node_modules/escodegen/escodegen.js:1880:34)
    at CodeGenerator.generateExpression (/home/me/project/node_modules/escodegen/escodegen.js:2456:28)
    at CodeGenerator.ExpressionStatement (/home/me/project/node_modules/escodegen/escodegen.js:1335:28)
    at CodeGenerator.generateStatement (/home/me/project/node_modules/escodegen/escodegen.js:2469:33)
    at CodeGenerator.Program (/home/me/project/node_modules/escodegen/escodegen.js:1717:43)
    at CodeGenerator.generateStatement (/home/me/project/node_modules/escodegen/escodegen.js:2469:33)
    at generateInternal (/home/me/project/node_modules/escodegen/escodegen.js:2490:28)
    at Object.generate (/home/me/project/node_modules/escodegen/escodegen.js:2558:18)
    at WorkFlowContext.generateCode (/home/me/project/node_modules/fuse-box/dist/commonjs/core/WorkflowContext.js:55:26)
```

**Comment by nchanged** [comment]
Hi! Are you using aliases?

**Comment by niieani** [comment]
@nchanged yes, I am. When I remove them it works, but I do need them.

**Comment by nchanged** [comment]
1) Are you on the latest fusebox? `1.3.123`
2) Using Babel?

**Comment by niieani** [comment]
Indeed, latest Fusebox and Babel.

**Comment by nchanged** [comment]
Oh.. I think I know what the issue it about. Are you sure that all your code goes through babel? Cuz it uses [this](https://github.com/fuse-box/fuse-box/blob/master/src/core/WorkflowContext.ts#L156) instead of using a custom generator [above](https://github.com/fuse-box/fuse-box/blob/master/src/core/WorkflowContext.ts#L153)

**Comment by niieani** [comment]
What could be causing some code not to go through babel? I'm just using the babel plugin, without any options.

**Comment by nchanged** [comment]
http://fuse-box.org/#babel-plugin
please read up here ^

you need to set `limit2project false`
