### ISSUE TITLE
Uglify error

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#419]
Hi, Am running the latest fusebox and uglifyjs plugin always gives me this error:

```
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)
    at js_error (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)
    at croak (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)
    at token_error (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)
    at expect_token (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2115:9)
    at expect (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2118:36)
    at eval (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2691:13)
    at eval (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)
    at expr_atom (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2621:35)
    at maybe_unary (eval at <anonymous> (/Users/tomi/Github/packages/webpack2-typescript/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)
```

My tsconfig.json is set to es5 with commonjs modules
I deleted the .fusebox cache

Removing the uglify plugin it builds and I can confirm that code inside is es5 with commonjs stuff.

Any idea what can be going wrong? Thanks. ...

**Comment by tomitrescak** [comment]
Since I was getting the same error with external uglify, I found out that the error was in your TypescriptHelpers and generator function. Uglify blew up on that.

**Comment by tomitrescak** [comment]
Hmm, it explodes on following (clearly not ES5):

This time is comes from the"buffer" package. I just do not get how this es6 notation made it to the vendor bundle.

```
arr.__proto__ = { __proto__: Uint8Array.prototype, foo() { return 42; } };
```

**Comment by tomitrescak** [comment]
Hmm, the original file in buffer: index.js contains following:

arr.__proto__ = {__proto__: Uint8Array.prototype, foo: function () { return 42 }}

yet following is bundled:

arr.__proto__ = { __proto__: Uint8Array.prototype, foo() { return 42; } };

WHY?

**Comment by tomitrescak** [comment]
Hm, it is a bug in your code guys.
I've found it in the dist folder > modules > buffer

```
arr.__proto__ = { __proto__: Uint8Array.prototype, foo() { return 42; } };
```

This breaks the uglify

**Comment by tomitrescak** [comment]
And nevermind .. I had fusebox and fuse-box in my project ... :/

**Comment by geowarin** [comment]
I've install fusebox a couple of times by mistake too :laughing:

**Comment by nchanged** [comment]
I will add it to the publish script ... ;)
