### ISSUE TITLE
Fresh install, simple config, then Error: Cannot find module 'source-map'

### ISSUE THREAD

**Issue by trusktr** [fuse-box/fuse-box#427]
I just `npm install fusebox`ed fusebox, then wrote a simple `fusebox.js` file in my project:

```js
const FuseBox = require('fusebox')

let fuse = FuseBox.init({
    homDir: './src',
    outDir: './fusebox_test',
    cache: true,
    log: false,
    debug: false,
})

fuse.bundle('> main.ts')
```

then it results in the error

```
> node fusebox.js
module.js:442
    throw err;
    ^

Error: Cannot find module 'source-map'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/dist/commonjs/plugins/SourceMapPlainJsPlugin.js:4:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by trusktr** [comment]
I was using webpack before, but I made sure to delete webpack.config.js to start from scratch, just to see what happens. Never used fusebox before.

Basically, I just have a `src` folder full of JS/TS files, and `tsconfig.json` is still in the root of my project.

`fusebox.js` is also at the root of my project, and I run it with `node fusebox.js` at the moment.

**Comment by trusktr** [comment]
Apparently updating from NPM v2 to NPM v4 solves this problem, and now I have a [new problem](https://github.com/fuse-box/fuse-box/issues/428).

**Comment by trusktr** [comment]
Actually, re-opening, because fixing this for NPM v2 might be nice for those users.

**Comment by aretecode** [comment]
@trusktr see right here https://github.com/fuse-box/fuse-box/blob/master/package.json#L31

**Comment by nchanged** [comment]
Please, feel free to re-open the issue,  if you are still experiencing any issues. Also, check the upcoming version `fuse-box@2.0.0-beta.8`
here http://fuse-box.org:3333/
