### ISSUE TITLE
TypeError: FuseBox.init is not a function

### ISSUE THREAD

**Issue by trusktr** [fuse-box/fuse-box#428]
I have a really simple fusebox.js file:

```js
const FuseBox = require('fusebox')

let fuse = FuseBox.init({
    homDir: './src',
    outDir: './fusebox_test',
    cache: true,
    log: false,
    debug: false,
})

fuse.bundle('> main.ts')
```

When running my `node fusebox.js` in my project, I get an error:

```
> node fusebox.js
/home/cit/imvu/website-project/website/src/sticker_creator/fusebox.js:4
let fuse = FuseBox.init({
                   ^

TypeError: FuseBox.init is not a function
    at Object.<anonymous> (/home/cit/imvu/website-project/website/src/sticker_creator/fusebox.js:4:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by trusktr** [comment]
It's supposed to be

```js
const FuseBox = require('fusebox').FuseBox
```

This is not apparent until http://fuse-box.org/#full-config. It should probably be near the top, in both CommonJS and ES6 format, to make it obvious.

**Comment by nchanged** [comment]
or

```
const { FuseBox } = require('fuse-box')
```

And please use `fuse-box` not `fusebox` for consitency
