### ISSUE TITLE
Error: Debug Failure. False expression: Output generation failed

### ISSUE THREAD

**Issue by trusktr** [fuse-box/fuse-box#430]
Some files give this error, not sure what it means:

```
Error: Debug Failure. False expression: Output generation failed
    at Object.assert (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/typescript/lib/typescript.js:3259:23)
    at Object.transpileModule (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/typescript/lib/typescript.js:76181:18)
    at File.handleTypescript (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/dist/commonjs/core/File.js:206:25)
    at File.consume (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/dist/commonjs/core/File.js:152:25)
    at ModuleCollection.resolve (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/dist/commonjs/core/ModuleCollection.js:159:18)
    at realm_utils_1.each (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/dist/commonjs/core/ModuleCollection.js:72:29)
    at iterateMap (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/node_modules/realm-utils/dist/commonjs/each.js:43:34)
    at /home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/node_modules/realm-utils/dist/commonjs/each.js:59:17
    at /home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/node_modules/realm-utils/dist/commonjs/each.js:63:14
    at Object.exports.Each [as each] (/home/cit/imvu/website-project/website/src/sticker_creator/node_modules/fusebox/node_modules/realm-utils/dist/commonjs/each.js:9:12)
```

**Comment by nchanged** [comment]
That's a typescript error. Any update on that?

**Comment by trusktr** [comment]
@nchanged No idea, but I don't get any errors when I use plain `webpack`. I got this error when I tried to use FuseBox. I'll post back if I hit it again in a future project.

**Comment by JosephAntoniou** [comment]
Issue relates to the request for a 'new' object in Typescript.

I have no issue compiling with 'tsc'. Running with 'ng serve' complains with the aforementioned stack trace. If I comment my 'new' out then it compiles.

I have a type definition for this but am not sure if there is anything actually wrong and why we have such discrepancies.

"

**Comment by daflair** [comment]
I got a similar error (slightly different stack-top) and traced it as follows:

**Condition:**
- using a `+ [… whatever]/**/*.ts` glob
- having a `.d.ts` file matching that glob
- I'm using 2.0.0-beta.6 with Typescript 2.4.0-dev.20170430

**Stack:**
``` log
Error: Debug Failure. False expression: Output generation failed
    at Object.assert (/usr/local/lib/node_modules/typescript/lib/typescript.js:3324:23)
    at Object.transpileModule (/usr/local/lib/node_modules/typescript/lib/typescript.js:80306:18)
    at File.handleTypescript (/Users/daflair/Projects/nerdy-app/node_modules/fuse-box/dist/commonjs/core/File.js:215:25)
    at File.consume (/Users/daflair/Projects/nerdy-app/node_modules/fuse-box/dist/commonjs/core/File.js:156:25)
    at ModuleCollection.resolve (/Users/daflair/Projects/nerdy-app/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:176:18)
    at realm_utils_1.each (/Users/daflair/Projects/nerdy-app/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:74:29)
    at iterateMap (/Users/daflair/Projects/nerdy-app/node_modules/realm-utils/dist/commonjs/each.js:43:34)
    at iterateMap (/Users/daflair/Projects/nerdy-app/node_modules/realm-utils/dist/commonjs/each.js:56:25)
    at iterateMap (/Users/daflair/Projects/nerdy-app/node_modules/realm-utils/dist/commonjs/each.js:56:25)
    at iterateMap (/Users/daflair/Projects/nerdy-app/node_modules/realm-utils/dist/commonjs/each.js:56:25)
```

**Resolution:**
Changed globs to `**/index.ts`

** Downside:**
If it is not imported by an index or it extension, it is not bundled!

**Comment by nchanged** [comment]
@daflair please upgrade to `fuse-box@2.0.0` it has been released ;-)

**Comment by eddow** [comment]
Yes, it's the .d.ts files that make a problem - and it is still present in 2.0 unfortunately ...
This is a hack to make things work :
"+ [whatever/**/*.ts] - whatever/**/*.d.ts"
