### ISSUE TITLE
Test runner

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#477]
Guys, I really like your test runner and it's speeeed. I'm already talking to Artem Govorov the developer of wallabyjs to include it in their pipeline. I also would like to include new matchers, such as "snapshot" matcher, which I already developed for mocha.

To do all this properly, is there any Extensibility and Execution API? Extensibility for matchers and execution for wallaby (at least to read the errors location and message)

Thanks!

**Comment by nchanged** [comment]
@tomitrescak that's so cool!!
Yeah, fuse tests are 100% customisable. You can make a custom reporter for example. We could extend it to run in the browser for example. By `Extensibility for matchers` you meant that

https://github.com/fuse-box/fuse-test-runner/blob/master/src/FuseBoxTestRunner.ts#L40 ?

that's the only place where it's hardcoded at the moment.  But other than that, please feel free to take a look at this [repo](https://github.com/fuse-box/fuse-test-runner)

**Comment by devmondo** [comment]
@tomitrescak yeah please man, FuseBox test runner is much better than what is out there, the only thing missing is wallaby.js. this would make us complete!!!

**Comment by tomitrescak** [comment]
Well I don't have the best of news as wallaby is closed system and does not allow for easy extensibility, Artem would consider fuse box test runner only after it will reach "certain popularity". Yet, nothing is lost, I can still come up with mappings onto mocha test runner. It will NOT use fuse-box to package the app though, yet use raw typescript output processed with mocha. This way you will still be able to run test with fuse box, but also use wallaby for in app testing. What do you think?

**Comment by devmondo** [comment]
@tomitrescak  this is a great start man!, if we can find a trade of solution until wallaby consider us worthy, it would be greatm thanks for your enthusiasm man :)

**Comment by tomitrescak** [comment]
I'm on it. One thing .. to fully understand what is happening under the hood I tried to setup debuggin session in VS Code. The breakpoints are hit only in the main fuse.js file, everything from there is not hitting it. I made sure that `sourceMaps: true` is set.

**Comment by tomitrescak** [comment]
First bit is done. Not sure where you want the contribution PR to be so here is description of what needs to be done:

1. You need to define wallaby transformer and save it in your root dir (it can become part of the fuse-box-test) package

```js
function loader(content, name) {
  var classReg = /export\s+class\s+(\w+Test)/g;
  name = name || '.';

  var matches = classReg.exec(content);

  if (matches) {
    content += `
function __runTests(test) {
  for (let method in test) {
    if (method.match(/${name}/)) {
      it(method, function () {
        test[method]();
      });
    }
  }
} 

`;

    while (matches) {
      content += `__runTests(new ${matches[1]}());\n`;
      matches = classReg.exec(content);
    }
  }
  return content;
}

module.exports.loader = loader;
```

Next bit is simply to include this transformer in the wallaby config:

```js
const transform = require("./fuse-test-transform").loader; // THIS IS NEW
const path = require('path');

module.exports = function (wallaby) {
  // var load = require;

  return {
    files: [
      "examples/testing/**/*.ts*",
      "!examples/testing/**/*.test.ts*"
    ],
    tests: [
      "examples/testing/**/*.test.ts*"
    ],
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ jsx: 'react', module: 'commonjs' })
    },
    preprocessors: {
      "**/*.ts": file => transform(file.content)  // THIS IS NEW
    },
    env: {
      type: "node"
    },
    testFramework: "mocha"
  };
};
```

E voila!

![screen shot 2017-05-04 at 10 03 39 am](https://cloud.githubusercontent.com/assets/2682705/25686371/0040c7aa-30b1-11e7-8824-aeab839edc21.png)

**Comment by tomitrescak** [comment]
I have also implemented snapshots, this I'll post as PR to fuse-test-runner

**Comment by tomitrescak** [comment]
And with this transform, you can even use fusebox snapshots in wallaby ;) Just make sure you includ eyour snapshots in your config:

```js
// wallaby.js
...
    tests: [
      "examples/testing/**/*.test.ts*",
      "__snapshots__/*.snap",
    ],
```

```js
var TestConfig = require('fuse-test-runner').TestConfig;


function loader(content, name) {
  var classReg = /export\s+class\s+(\w+Test)/g;
  name = name || '.';

  var matches = classReg.exec(content);

  if (matches) {
    content += `
const TestConfig = require('fuse-test-runner').TestConfig;
function __runTests(test, className) {
  for (let method in test) {
    if (method.match(/${name}/)) {
      it(method, function () {
        TestConfig.currentTask = {
          className,
          title: method
        }
        TestConfig.snapshotCalls = null;
        test[method]();
      });
    }
  }
} 

`;

    while (matches) {
      content += `__runTests(new ${matches[1]}(), '${matches[1]}');\n`;
      matches = classReg.exec(content);
    }
  }
  return content;
}

module.exports.loader = loader;
```

**Comment by nchanged** [comment]
@tomitrescak that's just pure awesomeness!
So wallaby executes it without actually running fusebox.test()

**Comment by tomitrescak** [comment]
That is correct. It works without the fusebox-test-runner ;)

**Comment by nchanged** [comment]
Cool, could make PR? ;-)

**Comment by devmondo** [comment]
@tomitrescak this is brilllllllllllllllllliant!!!! thanks a lot for it man :)

**Comment by tomitrescak** [comment]
Where do you want me to make the PR? Which package you reckon it belongs to ? And I guess only the "transformer" should be there. The wallaby config will be part of the docs?

**Comment by nchanged** [comment]
oh yeah!
i guess here https://github.com/fuse-box/fuse-test-runner ?!

**Comment by devmondo** [comment]
@tomitrescak do you have a full repo of this working ?

**Comment by tomitrescak** [comment]
I do, have it running with the LUIS. I'll post it this afternoon.

**Comment by tomitrescak** [comment]
I don't have full react testing stack ready yet though, as I miss those before all and after all hooks mentioned in #2

**Comment by tomitrescak** [comment]
Here is the repo, yet, the snapshots will not work for you as they depend on the changes from the PR:

https://github.com/tomitrescak/fuse-box-react-test-app

I am also a bit blocked by the global setup and teardown function proposed in the test repo. If you want to test react component folloowing needs to be injected into global:

```js
TestConfig.setup = () => {
    console.log('!!!!!!!! Setting up ...');
    var jsdom = require('jsdom').jsdom;

    var exposedProperties = ['window', 'navigator', 'document'];

    global.document = jsdom('');
    global.window = document.defaultView;
    Object.keys(document.defaultView).forEach((property) => {
      if (typeof global[property] === 'undefined') {
        exposedProperties.push(property);
        global[property] = document.defaultView[property];
      }
    });

    global.navigator = {
      userAgent: 'node.js'
    };
  }
```

**Comment by tomitrescak** [comment]
OKAY, I have included this afterAll and beforeAll in my PR. Luckily the only part that was touched was the fuseboxtestrunner component ... 4 lines added there. Yet I have used async/await notation, not sure if you are happy with that.

Anyways, the whole repo now works nicely in all three environments fuse(console) / wallaby / browser (luis). Check it out, I think it's really cool and veeeeery usefull:

1. During development you use Wallaby.JS
2. For presentation of your frontend components along with tests or if you have no money for wallaby, you can use LUIS.
3. For CI or any other super useful reason you use fuse test runner.

**Comment by nchanged** [comment]
@tomitrescak awesome job! You think you can help with docs [here](https://github.com/fuse-box/fuse-box/blob/master/docs/test-runner.md) ?

**Comment by devmondo** [comment]
@tomitrescak amazing job man!
thank you very much, we shall make an article about this and give credit to your contribution after we make the official 2.0 release

**Comment by devmondo** [comment]
@tomitrescak i cloned your react repo and ran it but i get this error any idea why ?
```
Wallaby App available at: http://wallabyjs.com/app/#/files
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\projects\Fuse-Box\fuse-box-react-test-app\node_modules\fuse-test-runner\dist\commonjs\FuseBoxTestRunner.js:11:20)
```

**Comment by tomitrescak** [comment]
@devmondo I did not have time to clean the project up over weekend .. give me a bit of time and I'll have a look. There must be something fishy with the transformer. Sorry about that ...

**Comment by devmondo** [comment]
@tomitrescak  or must be a fuse bug hahahha :)

**Comment by tomitrescak** [comment]
Guys, sorry for the delay, was busy with congress preparations. 

I just cloned the repo and upgraded the fuse-test-runner to 1.0.13 and all worked out of the box got all test running in wallaby and in wallaby app.

Can you confirm that all works for you ?

I am also preparing a rather large blog post on testing React front end with fuse-test-runner, will let you know before I post it for your review.

**Comment by nchanged** [comment]
@tomitrescak great news! if you planning on doing it on medium, would you consider submitting it over [here](https://medium.com/fusebox) ?

**Comment by devmondo** [comment]
@tomitrescak I upgraded to latest using your repo, but I still get this error with wallaby
```
SyntaxError: Unexpected token =
	at Object.setup setup.js:2
```

@nchanged i don't know if this log helps out
```
wallaby.js started
core v1.0.424
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\projects\Fuse-Box\fuse-box-react-test-app\node_modules\fuse-test-runner\dist\commonjs\FuseBoxTestRunner.js:11:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\projects\Fuse-Box\fuse-box-react-test-app\node_modules\fuse-test-runner\dist\commonjs\index.js:3:27)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.setup (.\setup.js:4:63)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:614:5)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\projects\Fuse-Box\fuse-box-react-test-app\node_modules\fuse-test-runner\dist\commonjs\FuseBoxTestRunner.js:11:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\projects\Fuse-Box\fuse-box-react-test-app\node_modules\fuse-test-runner\dist\commonjs\index.js:3:27)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.setup (.\setup.js:4:63)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:614:5)
Runtime error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\projects\Fuse-Box\fuse-box-react-test-app\node_modules\fuse-test-runner\dist\commonjs\FuseBoxTestRunner.js:11:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\projects\Fuse-Box\fuse-box-react-test-app\node_modules\fuse-test-runner\dist\commonjs\index.js:3:27)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.setup (.\setup.js:4:63)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:614:5)
```

**Comment by nchanged** [comment]
Worth a mention - you are running it on windows

**Comment by devmondo** [comment]
yep, windows, it seems transpiling is not kicking somehow!

**Comment by devmondo** [comment]
@tomitrescak @nchanged, I finally solved it! 
wallaby was using node version 4 by default. once I set it to latest, all worked out!

it is awesome, fully working and as fast as rocket!!! thank you very much, Mr. @tomitrescak
