### ISSUE TITLE
sass and postcss in fusebox

### ISSUE THREAD

**Issue by marko-mlinarevic** [fuse-box/fuse-box#526]
This is my code for css

`  
[
            SassPlugin({ importer: true }),
            PostCSS({
                plugins: [ 'autoprefixer' ],
            }),
            CSSPlugin({ group: 'app.css', outFile: './dist/app.css' })
        ]
`

I get error
`TypeError: plugin is not a function
    at LazyResult.run (E:\Stacks\fuseBox\node_modules\postcss\lib\lazy-result.js:270:20)
    at LazyResult.asyncTick (E:\Stacks\fuseBox\node_modules\postcss\lib\lazy-result.js:185:32)
    at processing.Promise.then._this2.processed (E:\Stacks\fuseBox\node_modules\postcss\lib\lazy-result.js:224:20)
    at LazyResult.async (E:\Stacks\fuseBox\node_modules\postcss\lib\lazy-result.js:221:27)
    at LazyResult.then (E:\Stacks\fuseBox\node_modules\postcss\lib\lazy-result.js:127:21)
    at PostCSSPluginClass.transform (E:\Stacks\fuseBox\node_modules\fuse-box\dist\commonjs\plugins\stylesheet\PostCSSPlugin.js:21:14)
    at tasks.push (E:\Stacks\fuseBox\node_modules\fuse-box\dist\commonjs\core\File.js:114:63)
    at context.queue.realm_utils_1.each.promise (E:\Stacks\fuseBox\node_modules\fuse-box\dist\commonjs\core\File.js:125:76)
    at iterate (E:\Stacks\fuseBox\node_modules\realm-utils\dist\commonjs\each.js:79:34)
    at E:\Stacks\fuseBox\node_modules\realm-utils\dist\commonjs\each.js:83:29
`
`
Error: Invalid mapping: {"generated":{"line":387,"column":16},"source":"../node_modules/bulma/sass/base/helpers.sass","original":{"line":67,"column":-4},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (E:\Stacks\fuseBox\node_modules\source-map\lib\source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (E:\Stacks\fuseBox\node_modules\source-map\lib\source-map-generator.js:101:12)
    at E:\Stacks\fuseBox\node_modules\concat-with-sourcemaps\index.js:60:28
    at Array.forEach (native)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (E:\Stacks\fuseBox\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Concat.add (E:\Stacks\fuseBox\node_modules\concat-with-sourcemaps\index.js:58:18)
    at BundleSource.addFile (E:\Stacks\fuseBox\node_modules\fuse-box\dist\commonjs\BundleSource.js:61:31)
    at files.forEach.f (E:\Stacks\fuseBox\node_modules\fuse-box\dist\commonjs\CollectionSource.js:18:33)
    at Array.forEach (native)
    at CollectionSource.get (E:\Stacks\fuseBox\node_modules\fuse-box\dist\commonjs\CollectionSource.js:17:15)
`

Can somebody explain these errors

**Comment by devmondo** [comment]
@marko-mlinarevic looks like a `postcss` plugin issue, are you sure you installed required `postcss` plugins?

in simple words, make sure you install any postcss's plugin you want to use as we don't ship them by default.

so i doubt you need to install `autoprefixer` plugin in your project.

**Comment by marko-mlinarevic** [comment]
I installed it already

my package.json file

`
  "dependencies": {
    "bulma": "^0.4.1",
    "fuse-box": "2.0.0-beta.22",
    "node-sass": "^4.5.2",
    "typescript": "^2.3.2",
    "vue": "~2.3.2",
    "vue-template-compiler": "~2.3.2",
    "autoprefixer": "^7.0.1",
    "postcss": "^6.0.1",
    "vue-template-es2015-compiler": "~1.5.2"
  },
  "devDependencies": {
    "autoprefixer": "^7.0.1",
    "postcss": "^6.0.1"
  }`

**Comment by nchanged** [comment]
@marko-mlinarevic are you sure your config is wrapped?

```js
plugins : [

 [ SassPlugin({ importer: true }), PostCSS({ plugins: [ 'autoprefixer' ], }), CSSPlugin({ group: 'app.css', outFile: './dist/app.css' }) ]
// ^ NOTE []
]
```
+ maybe ` PostCSS({ plugins: [require( 'autoprefixer') ], })` ?

**Comment by marko-mlinarevic** [comment]
I needed to do this 

`[require( 'autoprefixer')`

now this is passing
