### ISSUE TITLE
ElementUI library usage throws error document not defined

### ISSUE THREAD

**Issue by marko-mlinarevic** [fuse-box/fuse-box#529]
I'm trying to add ElementUI framework that is built on vue to the project. This is my fuse.js file

```
const { FuseBox, VuePlugin, SassPlugin, CSSPlugin, WebIndexPlugin, Sparky, PostCSS, BabelPlugin } = require('fuse-box');
const autoprefixer  = require('autoprefixer');
const axios = require('axios');
const vuex = require('vuex');
const modernizr = require('modernizr');
const ElementUI = require('element-ui');

const fuse = FuseBox.init({
    homeDir: './src',
    output: 'dist/$name.js',
    plugins: [
        VuePlugin(),
        axios,
        vuex,
        modernizr,
        require('element-ui'),
        BabelPlugin({
            presets: ["es2015"]
        }),
        [
            SassPlugin({ importer: true }),
            PostCSS({
                plugins: [ autoprefixer ],
                parser: {},
            }),
            CSSPlugin({ group: 'app.css', outFile: './dist/app.css' })
        ],
        WebIndexPlugin({ template: './src/index.html' })
    ]
})

fuse.dev()

fuse.bundle('app.js')
    .instructions('> index.ts')
    .watch()

fuse.run()

Sparky.task('default', () => {
    return Sparky.watch('./assets', { base: './src' })
        .dest('./dist')
})
```

and this is my error log

```
var ieVersion = isServer ? 0 : Number(document.documentMode);
                                      ^

ReferenceError: document is not defined
    at Object.<anonymous> (E:\Stacks\fuseBox\node_modules\element-ui\lib\utils\dom.js:22:39)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Stacks\fuseBox\node_modules\element-ui\lib\utils\popup\popup-manager.js:9:12)
    at Module._compile (module.js:573:32)

```

**Comment by nchanged** [comment]
Hi,
What is `require('element-ui')` on the fuse plugin list? You can't put non-fusebox plugin there.

**Comment by devmondo** [comment]
@marko-mlinarevic all of the below should be required in your app code and not `fuse.js`
```
const axios = require('axios');
const vuex = require('vuex');
const modernizr = require('modernizr');
const ElementUI = require('element-ui');
```
and all should work

**Comment by marko-mlinarevic** [comment]
now I get this 

⠼ dev server running http://localhost:4444{ message: 'File contents for E:\\Stacks\\fuseBox\\node_modules\\axios\\package.json were not loaded. Missing a plugin?' }

**Comment by devmondo** [comment]
@marko-mlinarevic  you forgot to add [`JSONPlugin`](http://fuse-box.org/plugins/json-plugin) to fuse :)

**Comment by marko-mlinarevic** [comment]
That solved it... thanks, and I'm officially going to move from webpack to fusebox

**Comment by devmondo** [comment]
@marko-mlinarevic thank you very much for putting your trust and patience in us, we hope that we will keep you happy :)
