### ISSUE TITLE
fuse-box ignoring 'extends' in tsconfig.json

### ISSUE THREAD

**Issue by xaviergonz** [fuse-box/fuse-box#590]
Hi, i just noticed that "when a tsconfig file uses "extends" it gets ignored when using fuse-box, yet works correctly when using tsc directly.

For example, say I have these two files:
../tsconfig.json, with compiler options such as "jsx": "React"
./tsconfig.json, with "extends": "../tsconfig.json"

If I run tsc againt .tsx files it works correctly, since ./tsconfig correctly extends the base one.
Fuse-box fails with 
```
  → Typescript config:  \tsconfig.json
Acorn error: Unexpected token (75:51)
```

but if I remove the extends and move the "jsx": "React" to the local file then it works correctly.

**Comment by nchanged** [comment]
Hi, Could you provide an example with `extends` because FuseBox reads is a bit differently than typescript

**Comment by nchanged** [comment]
Closing due to inactivity

**Comment by xaviergonz** [comment]
Sorry for the inactivity.
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
section Configuration inheritance with extends
```
{
  "extends": "./configs/base",
  ...
}
```

basically extends makes a deep merge of the tsconfig in "extends" with the current tsconfig.json

**Comment by nchanged** [comment]
The current version uses typescript to read the config. So it should extend it correctly. (That's just my assumption)

**Comment by unional** [comment]
I confirm that it does not process "extends" correctly.

```js
// tsconfig.build.json
{
  "compileOptions": {
      // all options
   }
}
// tsconfig.json
{
  include: [
    "src"
  ]
}
```

When running fuse, it fails with error: `TypeScript automatic transpilation has failed`.


This causes user can't use `fuse` in monorepo such as https://github.com/RyanCavanaugh/learn-a

**Comment by unional** [comment]
I saw this:

https://github.com/fuse-box/fuse-box/blob/4220dccb215fc4c225d1364e4b5ba0710ddc36fd/src/core/TypescriptConfig.ts#L113

My guess is the supplied callback is the problem.

**Comment by unional** [comment]
This should solve the problem:

```ts
const res = ts.readConfigFile(this.configFile, ts.sys.readFile);
config = ts.parseJsonConfigFileContent(res.config, ts.sys, this.context.appRoot)
```

However, I got a bunch of failed tests. Need to figure out why.

**Comment by unional** [comment]
btw I notice the tests are somehow flaky. Without any change, sometime I get the tests passes but sometime has these two failure:

```sh
      ✗ Should dynamically split css file
          Expected the original
          []
          to be deep equal to
          [
            "/styles.css"
          ]
          Error: Expected the original
          []
          to be deep equal to
          [
            "/styles.css"
          ]
              at ShouldInstance.deepEqual (/Users/hwong/code/unional/fuse-box/.fusebox/tests/1539764356705/test.js:28235:19)
              at Should dynamically split css file.quantumEnv (/Users/hwong/code/unional/fuse-box/.fusebox/tests/1539764356705/test.js:22835:45)

      ✗ Should dynamically split css file (different folder without slash)
          Expected the original
          [
            "chunks/ea9fe601.css"
          ]
          to be deep equal to
          [
            "chunks/ea9fe601.css",
            "/styles.css"
          ]
          Error: Expected the original
          [
            "chunks/ea9fe601.css"
          ]
          to be deep equal to
          [
            "chunks/ea9fe601.css",
            "/styles.css"
          ]
              at ShouldInstance.deepEqual (/Users/hwong/code/unional/fuse-box/.fusebox/tests/1539764356705/test.js:28235:19)
              at Should dynamically split css file (different folder without slash).quantumEnv (/Users/hwong/code/unional/fuse-box/.fusebox/tests/1539764356705/test.js:22856:48)
```
