### ISSUE TITLE
fusing error with 'rectangular' package (Angular2 example)

### ISSUE THREAD

**Issue by Tenvan** [fuse-box/fuse-box#601]
following runtime-error on fusing with package 'ractangular':

```
Connecting to fusebox HMR at ws://localhost:4445
vendor.js:111233 Uncaught TypeError: Cannot read property 'Point' of undefined
    at Number.<anonymous> (vendor.js:111233)
    at c (vendor.js:148966)
    at w.require (vendor.js:148966)
    at Number.<anonymous> (todo-item.component.ts:4)
    at c (vendor.js:148966)
    at w.require (vendor.js:148966)
    at Number.<anonymous> (app.module.ts:13)
    at c (vendor.js:148966)
    at w.require (vendor.js:148966)
    at Number.<anonymous> (main.ts:9)
vendor.js:148966 rectangular not found on request
i.onreadystatechange @ vendor.js:148966
vendor.js:115 Connected
```

with the following workaround it works in older versions (2.0 and older)):

```
fuse.register('rectangular', {homeDir: 'node_modules/rectangular', main: 'index.js', instructions: '**/**.js'});
```

but now you get follwing fusing error:

```
vendor ->
app ->
→\src\tsconfig.jsonTypescript config:  \src\tsconfig.json
→\src\tsconfig.jsonTypescript config:  \src\tsconfig.json
└──  (9 files,  43.7 kB) default
     main.js
     main.scss
     app.module.js
     app.component.js
     todo/todo-filter.pipe.js
     todo/todo-item.component.js
     todo/todo.model.js
     todo/todo-list.component.js
     todo/todo.service.js
Size: 43.7 kB in 835ms
TypeError: Cannot read property 'entryFile' of undefined
    at Function.onNode (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\plugins\OwnBundle.js:13:28)
    at plugins.forEach.plugin (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:80)
    at Array.forEach (native)
    at pre (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:78:55)
    at visit (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\ASTTraverse.js:18:23)
    at Function.traverse (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\ASTTraverse.js:41:9)
    at FileAnalysis.analyze (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\analysis\FileAnalysis.js:77:35)
    at File.makeAnalysis (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\File.js:152:23)
    at File.consume (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\File.js:178:22)
    at info.bundleData.including.forEach (D:\Node\Recherche\fuse-box-angular2-example\node_modules\fuse-box\dist\commonjs\core\ModuleCollection.js:119:30)
└──  (0 files,  53 Bytes) default
Size: 53 Bytes in 2s 166ms

---------------------------------------------------
Development server running http://localhost:4445
---------------------------------------------------
```

see on angular2-example fork in develop-branch: https://github.com/Tenvan/angular2-example

**Comment by nchanged** [comment]
Thanks, milestoned

**Comment by vegarringdal** [comment]
@nchanged 
fyi
This will break the Aurelia-seed if anyone tries it
in case someone complains about the seed in gitter

**Comment by vegarringdal** [comment]
Any update on this ? 
Is there a fix in the beta ?

**Comment by nchanged** [comment]
Was fixed =)
