### ISSUE TITLE
Enabling Quantum plugin triggers error from node-formidable

### ISSUE THREAD

**Issue by rosensama** [fuse-box/fuse-box#623]
Seems like node-formidable has a "special" test hook.   Can find issues from a few years ago where this can be remedied by a config in webpack.  Is there an equivalent way to toggle the global var for their test hook?   Note I only hit this bundling for dist using QuantumPlugin. 

See https://github.com/felixge/node-formidable/issues/295 

```
Uncaught ReferenceError: global is not defined
```

Offending code
```
global.GENTLY && (require = GENTLY.hijack(require));
```

Suggested webpack fix:
```
new DefinePlugin({ "global.GENTLY": false })
```

I use 
```
            QuantumPlugin({
                removeExportsInterop: false,
                uglify: true
            })
```

**Comment by nchanged** [comment]
@rosensama You can solve it now with the ReplacePlugin
`ReplacePlugin({ "global.GENTLY" : "false" })`

http://fuse-box.org/plugins/replace-plugin#usage

**Comment by rosensama** [comment]
Thanks.   This was what I was asking for.   But i don't get the expected result and it's sensitive to how it's sequenced.

If I run it before the JSONPlugin I get the following . . .
```
        plugins: [
            ReplacePlugin({"global.GENTLY" : "false"}),
            SVGPlugin(),
            JSONPlugin(),
            CSSPlugin(),
            BabelPlugin(),
            WebIndexPlugin({
                template: "src/index.html"
            }),
            isProduction && QuantumPlugin({
                removeExportsInterop: false,
                uglify: true
            })
        ]
```
```
17:10:08: ReplacePluginClass : Captured db.json
{ message: 'File contents for /home/rosensama/src/the_project/node_modules/mime-db/db.json were not loaded. Missing a plugin?' }
└──  (0 files,  53 Bytes) default
size: 53 Bytes in 2s 393ms
TypeError: Cannot read property 'replace' of undefined
    at ReplacePluginClass.transform (/home/rosensama/src/the_project/node_modules/fuse-box/dist/commonjs/plugins/ReplacePlugin.js:13:46)
    at tasks.push (/home/rosensama/src/the_project/node_modules/fuse-box/dist/commonjs/core/File.js:128:59)
    at context.queue.realm_utils_1.each.promise (/home/rosensama/src/the_project/node_modules/fuse-box/dist/commonjs/core/File.js:132:76)
    at iterate (/home/rosensama/src/the_project/node_modules/realm-utils/dist/commonjs/each.js:79:34)
    at /home/rosensama/src/the_project/node_modules/realm-utils/dist/commonjs/each.js:92:16
    at Object.exports.Each [as each] (/home/rosensama/src/the_project/node_modules/realm-utils/dist/commonjs/each.js:9:12)
    at File.tryPlugins (/home/rosensama/src/the_project/node_modules/fuse-box/dist/commonjs/core/File.js:132:53)
    at File.consume (/home/rosensama/src/the_project/node_modules/fuse-box/dist/commonjs/core/File.js:198:14)
    at ModuleCollection.resolve (/home/rosensama/src/the_project/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:176:18)
    at realm_utils_1.each.name (/home/rosensama/src/the_project/node_modules/fuse-box/dist/commonjs/core/ModuleCollection.js:186:29)
```
If I place it after JSONPlugin and before BabelPlugin, the bundling fails in the QuantumPlugin processing.  I've tried removing `.fusebox` and reinstall acorn.  
```
        plugins: [
            SVGPlugin(),
            JSONPlugin(),
            CSSPlugin(),
            ReplacePlugin({"global.GENTLY" : "false"}),
            BabelPlugin(),
            WebIndexPlugin({
                template: "src/index.html"
            }),
            isProduction && QuantumPlugin({
                removeExportsInterop: false,
                uglify: true
            })
        ]
```

```
  → Generating abstraction, this may take a while
SyntaxError: Unexpected token (29:19)
    at Parser.pp$4.raise (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:2549:13)
    at Parser.pp.unexpected (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:635:8)
    at Parser.pp$3.parseExprAtom (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:2068:10)
    at Parser.parseExprAtom (/home/rosensama/src/the_project/node_modules/acorn-jsx/inject.js:392:24)
    at Parser.pp$3.parseExprSubscripts (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:1929:19)
    at Parser.pp$3.parseMaybeUnary (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:1906:17)
    at Parser.pp$3.parseExprOp (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:1867:41)
    at Parser.pp$3.parseExprOps (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:1850:90)
    at Parser.pp$3.parseMaybeConditional (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:1831:19)
    at Parser.pp$3.parseMaybeAssign (/home/rosensama/src/the_project/node_modules/acorn/dist/acorn.js:1806:19)
```

If I move it after BabelPlugin and before QuantumPlugin again it completes, but I get the same issue and `global.GENTLY` hasn't been replaced in vendor.js
```
        plugins: [
            SVGPlugin(),
            JSONPlugin(),
            CSSPlugin(),
            BabelPlugin(),
            WebIndexPlugin({
                template: "src/index.html"
            }),
            ReplacePlugin({"global.GENTLY" : "false"}),
            isProduction && QuantumPlugin({
                removeExportsInterop: false,
                uglify: true
            })
        ]

```

**Comment by nchanged** [comment]
Could u the try limiting ReplacePluginf to js files with chaining? I will fix it when I get to my laptop

**Comment by nchanged** [comment]
`2.2.0-beta.13`

Should be the first one.
```
["*.js", ReplacePlugin({"global.GENTLY" : "false"}) ]
```

**Comment by rosensama** [comment]
@nchanged thanks.   I'll test this over the next few days.

**Comment by rosensama** [comment]
@nchanged ran out of time this round to test this one further.   Have removed QuantumPlugin for now.

**Comment by nchanged** [comment]
Closing this issue for now. Feel free to re-open elsewise.
