### ISSUE TITLE
TypeError: reference.stopAndPersist is not a function

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#655]
Following `fuse.js` generates an error in my build: 

```js
const {
  EnvPlugin,
  FuseBox,
  QuantumPlugin,
  VuePlugin,
  WebIndexPlugin,
} = require('fuse-box');

const isProduction = process.env.NODE_ENV === 'production';

const fuse = FuseBox.init({
  homeDir: 'src',
  output: 'build/$name.js',
  hash: isProduction,
  cache: !isProduction,
  plugins: [
    EnvPlugin({ NODE_ENV: isProduction ? 'production' : 'development' }),
    isProduction && QuantumPlugin({ uglify: true }),
    VuePlugin(),
    WebIndexPlugin(),
  ],
});

fuse.bundle('vendor').instructions(`~ index.ts`);
fuse.bundle('app').instructions(`!> [index.ts]`);
fuse.run();
```

generates

```sh
Launching quantum core
  → Generating abstraction, this may take a while
  → Abstraction generated
  → Process bundle vendor
  → Process package default 
  →   Files: 0 
  → Process package vue 
  →   Files: 1 
  → Process package process 
  →   Files: 1 
  → Process package object-assign-polyfill 
  →   Files: 1 
  → Process bundle app
  → Process package default 
  →   Files: 1 
  → Render bundle vendor
  → Render bundle app
  ⠋ Uglifying vendor...TypeError: reference.stopAndPersist is not a function
    at Log.stopSpinner (/Users/me/Development/project/node_modules/fuse-box/dist/commonjs/Log.js:160:23)
    at BundleWriter.uglifyBundle (/Users/me/Development/project/node_modules/fuse-box/dist/commonjs/quantum/plugin/BundleWriter.js:55:23)
    at realm_utils_1.each (/Users/me/Development/project/node_modules/fuse-box/dist/commonjs/quantum/plugin/BundleWriter.js:110:26)
    at iterateMap (/Users/me/Development/project/node_modules/realm-utils/dist/commonjs/each.js:43:34)
    at /Users/me/Development/project/node_modules/realm-utils/dist/commonjs/each.js:59:17
    at /Users/me/Development/project/node_modules/realm-utils/dist/commonjs/each.js:63:14
    at Promise (<anonymous>)
    at Object.exports.Each [as each] (/Users/me/Development/project/node_modules/realm-utils/dist/commonjs/each.js:9:12)
    at BundleWriter.process (/Users/me/Development/project/node_modules/fuse-box/dist/commonjs/quantum/plugin/BundleWriter.js:97:30)
    at producer.generateAbstraction.then.then.then.then.then (/Users/me/Development/project/node_modules/fuse-box/dist/commonjs/quantum/plugin/QuantumCore.js:75:32)
```

Especially the `{ uglify: true }` part in `QuantumPlugin({ uglify: true })`. If I remove `{ uglify: true }` then the build runs but the generated bundle is not minified.

**Comment by nchanged** [comment]
Should be fixed here - `fuse-box@2.2.1-beta.3`
