### ISSUE TITLE
Quantum: _ponyfill2.default is not a function

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#682]
I am using the latest version of `fuse-box`: 2.2.1
Gist with my [fuse.js](https://gist.github.com/screendriver/c8160c2d036adfe640edc229ae9c34e5)
Error message (at runtime in my browser console)

```
10f62916-vendor.js:3081 Uncaught TypeError: (0 , _ponyfill2.default) is not a function
    at $fsx.f.(anonymous function) (http://127.0.0.1:8080/10f62916-vendor.js:3081:40)
    at Object.$fsx.r (http://127.0.0.1:8080/334ab48d-api.js:21:9)
    at $fsx.f.(anonymous function) (http://127.0.0.1:8080/10f62916-vendor.js:3060:23)
    at Object.$fsx.r (http://127.0.0.1:8080/334ab48d-api.js:21:9)
    at $fsx.f.(anonymous function) (http://127.0.0.1:8080/10f62916-vendor.js:2644:30)
    at Object.$fsx.r (http://127.0.0.1:8080/334ab48d-api.js:21:9)
    at $fsx.f.(anonymous function) (http://127.0.0.1:8080/10f62916-vendor.js:2612:25)
    at Object.$fsx.r (http://127.0.0.1:8080/334ab48d-api.js:21:9)
    at Children.only (http://127.0.0.1:8080/10f62916-vendor.js:1849:99)
    at $fsx.f.(anonymous function) (http://127.0.0.1:8080/10f62916-vendor.js:1853:2)
```

I looked at the generated bundle at line `3081` and saw this:

```js
// symbol-observable/lib/index.js
$fsx.f[38] = function(module,exports){
var _ponyfill = $fsx.r(39);
var _ponyfill2 = _interopRequireDefault(_ponyfill);
function _interopRequireDefault(obj) {
    return obj && obj.__esModule ? obj : { 'default': obj };
}
var root;
if (typeof self !== 'undefined') {
    root = self;
} else if ('object' !== 'undefined') {
    root = window;
} else if ('undefined' !== 'undefined') {
    root = global;
} else if ('object' !== 'undefined') {
    root = module;
} else {
    root = Function('return this')();
}
var result = (0, _ponyfill2['default'])(root); // this line throws the error
exports['default'] = result;
}
```

I asked where this dependency is coming from:

```
❯ yarn why symbol-observable
yarn why v0.27.5
[1/4] Why do we have the module "symbol-observable"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
info Reasons this module exists
   - "redux" depends on it
   - "lint-staged#listr#rxjs" depends on it
```

If you need more informations please let me know.

**Comment by nchanged** [comment]
http://fuse-box.org/page/quantum#removeexportsinterop
you need to set it to false

**Comment by nchanged** [comment]
My god, it feels like we need to detect React users and automatically set it to `false`. FuseBox removes non-standard things

**Comment by screendriver** [comment]
Oh wow, that was quick. Thank you! It works.

> it feels like we need to detect React users

Or highlight it more in the docs 😉 (write it at the top for example with a bold header like _"Warning for React users"_ or something else)
