### ISSUE TITLE
Test runner doesn't work with sourcemaps, and no warning is given

### ISSUE THREAD

**Issue by nspaeth** [fuse-box/fuse-box#721]
If you have sourcemaps enabled on the fuse instance, you get an unhelpful error like this:

```bash
TypeError: Cannot read property 'import' of undefined
    at BundleTestRunner.start (/home/nlspaeth/projects/fuse-box-examples/node_modules/fuse-box/dist/commonjs/BundleTestRunner.js:14:44)
    at Bundle.fuse.bundle.instructions.completed.proc [as onDoneCallback] (/home/nlspaeth/projects/fuse-box-examples/node_modules/fuse-box/dist/commonjs/core/Bundle.js:148:20)
    at fuse.initiateBundle (/home/nlspaeth/projects/fuse-box-examples/node_modules/fuse-box/dist/commonjs/core/Bundle.js:158:26)
    at output.writeCurrent.then (/home/nlspaeth/projects/fuse-box-examples/node_modules/fuse-box/dist/commonjs/core/WorkflowContext.js:351:21)
    at <anonymous>
```
This is do the lines in `core/Bundle.js`:
```javascript
211  const bundle = require(proc.filePath);
212  let runner = new BundleTestRunner(bundle, opts);
```
where `proc.filePath` is `/home/nlspaeth/projects/fuse-box-examples/.fusebox/tests/1502408662699/test.js.map`.

You can see an example at https://github.com/nspaeth/fuse-box-examples/tree/master/examples/testing

Ideally sourcemaps wouldn't interfere at all.

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
