### ISSUE TITLE
2.2.1 broke proc.start with sourcemaps

### ISSUE THREAD

**Issue by magnushiie** [fuse-box/fuse-box#727]
With 2.2.0 my project was working with sourcemaps and `Bundle.completed(proc => proc.start())`, e.g.:
```ts
  const fuse = FuseBox.init({
    sourceMaps: true,
    // ...snip...
  });
  const bundle = fuse.bundle(name);
  bundle.completed(proc => proc.start());
```

After upgrading to 2.2.1, I'm getting errors:

```log
dist\server.js.map:1
(function (exports, require, module, __filename, __dirname) { {"version":3,"sources":["/src/server/server.ts","/src/render-config.ts","/src/server/render-config-server.ts","/src/data/banklink.ts","/src/server/AppHandler.tsx","/src/App.tsx","/src/AppState.ts","/src/routing.ts","/src/graphql/client.ts","/src/pages/home.tsx","/src/components/AlternatingSections.tsx","/src/context.ts","/src/utils.ts","/src/design/colors.ts","/src/components/Link.tsx","/src/components/Button.tsx","/src/components/PageHeader.tsx","/src/TypeStyle.ts","/src/components/BankLink.tsx","/src/components/Row.tsx","/src/pages/menus.tsx","/src/components/FontAwesomeSymbol.tsx","/src/data/recipes.ts","/src/data/recipes/arepad-veiseliha-ja-kirsstomatitega/index.tsx","/src/data/recipes/kana-gremolata-spargli-ja-suvikorvitsaga/index.tsx","/src/data/recipes/orzo-pastaga-taidetud-paprikad/index.tsx","/src/data/recipes/quesadillad-kana-ja-paprikaga/index.tsx","/src/data/recipes/sarapuup

SyntaxError: Unexpected token :
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

It seems it's trying to run the sourcemap instead of the bundle. And `proc.filePath` inside the `completed` callback also points to the sourcemap.

**Comment by nchanged** [comment]
Hm, could you provide a sample repo? Or having sourceMaps : true will be enough to reproduce the issue?

**Comment by nchanged** [comment]
No worries, i managed to reproduce it

**Comment by nchanged** [comment]
`fuse-box@2.2.2-beta.13`
