### ISSUE TITLE
libsass - Mixins with compound "&" selectors make sourcemaps invalid

### ISSUE THREAD

**Issue by jezikk** [fuse-box/fuse-box#836]
Hi,

I have a project that works with latest stable version of fuse-box 2.2.31 without any problem:
```
https://github.com/jezikk/fuse-box-foundation-starter
``` 
After updating to beta version 2.3.1-beta.19 (using fuse-box@beta), there are errors during SASS compilation:
```
Error: Invalid mapping: {"generated":{"line":4,"column":70397},"source":"/node_modules/foundation-sites/scss/components/_button.scss","original":{"line":150,"column":-8},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\source-map\lib\source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\source-map\lib\source-map-generator.js:101:12)
    at C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\concat-with-sourcemaps\index.js:60:28
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\source-map\lib\source-map-consumer.js:155:14)

    at Concat.add (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\concat-with-sourcemaps\index.js:58:18)
    at group.subFiles.forEach.file (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\fuse-box\dist\commonjs\plugins\stylesheet\CSSplugin.js:51:20)
    at Array.forEach (<anonymous>)
    at CSSPluginClass.transformGroup (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\fuse-box\dist\commonjs\plugins\stylesheet\CSSplugin.js:49:24)
    at promises.push.Promise (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\fuse-box\dist\commonjs\core\ModuleCollection.js:168:59)
```

```
Error: Invalid mapping: {"generated":{"line":15,"column":70397},"source":"/node_modules/foundation-sites/scss/components/_button.scss","original":{"line":150,"column":-8},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\source-map\lib\source-map-generator.js:289:13)
    at SourceMapGenerator_addMapping [as addMapping] (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\source-map\lib\source-map-generator.js:101:12)
    at C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\concat-with-sourcemaps\index.js:60:28
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\source-map\lib\source-map-consumer.js:155:14)

    at Concat.add (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\concat-with-sourcemaps\index.js:58:18)
    at BundleSource.addFile (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\fuse-box\dist\commonjs\BundleSource.js:66:31)
    at files.forEach.f (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\fuse-box\dist\commonjs\CollectionSource.js:18:33)
    at Array.forEach (<anonymous>)
    at CollectionSource.get (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\node_modules\fuse-box\dist\commonjs\CollectionSource.js:17:15)
```

If you need any other information, please let me know.

Thanks,
Michal

**Comment by nchanged** [comment]
https://github.com/sass/libsass/issues/2312

**Comment by nchanged** [comment]
Seems to be quite a problem...
```
@mixin FormField {
  position: relative;
  display: flex;
  line-height: $Pollicino-FormField-height;

  &-label {     // <---- that's where the error is coming from
```

**Comment by nchanged** [comment]
It seems that it cannot be fixed at this stage, simply nothing we can do but wait. Node-sass states "bug confirmed" but when they are going to fix it - nobody knows.
Do you think you can use `.css` version for now?

**Comment by jezikk** [comment]
As I use only one root app.scss file and all other sass files are included in this file, I don't need grouping at all. So this workaround works great. Thank you for help.
