### ISSUE TITLE
Tilde alias

### ISSUE THREAD

**Issue by linde12** [fuse-box/fuse-box#848]
Hi, i am trying to migrate from webpack to fuse-box due to it's amazing hot-reload that actually works for React 16.

I have a problem where my project uses ~ (tilde) as an alias for "source root" (src/). In webpack this enabled me to type `import Clock from '~/components/Clock'`. When i try to do the same with fuse-box using `.alias('~', 'src')` i get an error (might be because tilde is treated specially?)

The error i'm getting looks like this:
```
TypeError: this[type] is not a function
    at CodeGenerator.generateExpression (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:2459:28)
    at CodeGenerator.CallExpression (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:1880:34)
    at CodeGenerator.generateExpression (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:2459:28)
    at CodeGenerator.ExpressionStatement (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:1335:28)
    at CodeGenerator.generateStatement (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:2472:33)
    at CodeGenerator.Program (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:1717:43)
    at CodeGenerator.generateStatement (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:2472:33)
    at generateInternal (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:2493:28)
    at Object.generate (/home/ocalinde/work/git/nb-pacs-hw/node_modules/escodegen/escodegen.js:2561:18)
    at WorkFlowContext.generateCode (/home/ocalinde/work/git/nb-pacs-hw/node_modules/fuse-box/dist/commonjs/core/WorkflowContext.js:149:26)
```

I've tried some different approaches but i can't get it right. It would be sweet to be able to just switch from webpack, i'm sure others agree.

When i used webpack i used a babel plugin called module-alias, but it seems to have no effect in fuse-box. I tried to see if i could get it working with fuse-box using the fuse-box BabelPlugin, but the docs just print a page with an empty object(`{}`) for me :(

Any help appreciated!

**Comment by linde12** [comment]
Oh, i found something over here: https://github.com/fuse-box/fuse-box/blob/master/docs/plugins/transpilers/BabelPlugin.md

After adding my babel-configuration like in the example the browser tried to request the file via XMLHttpRequest.

```
vendor.js:109288 ./src/components/Clock not found on request
```

**Comment by nchanged** [comment]
@linde12 tilde is already integrated into FuseBox. Remove all your aliases, and continue using tilde.

**Comment by nchanged** [comment]
@linde12 and try this option http://fuse-box.org/page/configuration#usetypescriptcompiler that will remove the need in Babel

**Comment by linde12** [comment]
@nchanged I see, i got another error because i was using the typescript compiler so i assumed it was related to the tilde.

Using the typescript compiler i have to type `import * as Bla from 'bla'` which is kind of annoying for people who are not using typescript. If i use baben en disable the typscript compiler i get different errors and don't get any sourcemaps or code at all in the debugger in chrome. I just get an empty "default" file.

The issue with the tilde was solved, but with the solution the app crashes for different reasons.

**Comment by nchanged** [comment]
@linde12 you should follow javascript standards, import module from "./module" which doesn't export default is a non-standard and a *uck up that babel made.

**Comment by nchanged** [comment]
Read this one carefully https://medium.com/fusebox/do-you-really-need-babel-baa0971f1957

**Comment by linde12** [comment]
@nchanged Yes, i read the typescript issue about it, but de facto standard is the one that babel set. I mean in all code samples i've seen it's being used "the babel way", one example is https://reactjs.org/tutorial/tutorial.html

Even the typescript community itself seem to have very different views on this.

It would be nice with some sort of compatibility layer to solve this for migrating users. Even if it's "wrong".

**Comment by nchanged** [comment]
@linde12 You can do anything with FuseBox
http://fuse-box.org/page/configuration#polyfillnonstandarddefaultusage

**Comment by linde12** [comment]
This is what i am after @nchanged, great i will try it out! Thanks for your help!
