### ISSUE TITLE
Adding babel-preset-expo fails to build.

### ISSUE THREAD

**Issue by pyros2097** [fuse-box/fuse-box#882]
I tried using the babel-preset-expo in my fuse-box project but this is the error I'm getting.  
```js
--- FuseBox 2.3.3 ---
{ TypeError: unknown: Property value expected type of string but got null
    at Object.validate (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-types/lib/definitions/index.js:161:13)
    at validate (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-types/lib/index.js:466:7)
    at PluginPass.JSXOpeningElement (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-plugin-transform-react-jsx-source/lib/index.js:35:68)
    at newFn (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/context.js:108:19) _babel: true }
{ TypeError: unknown: Property value expected type of string but got null
    at Object.validate (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-types/lib/definitions/index.js:161:13)
    at validate (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-types/lib/index.js:466:7)
    at PluginPass.JSXOpeningElement (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-plugin-transform-react-jsx-source/lib/index.js:35:68)
    at newFn (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/home/pyros2097/Code/mine/cress/packages/cress-cli/node_modules/babel-traverse/lib/context.js:108:19) _babel: true }
```
This is how I've configure the plugin,
```js
 BabelPlugin({
        test: /\.jsx$/,
        config: {
          sourceMaps: true,
          presets: ['expo'],
        },
 })
```
But babel-preset-env seems to work fine though. Don't know if this is related to fusebox. I'm trying to use a universal configuration with works for both web and react-native. As far as I know preset expo works with webpack.

**Comment by nchanged** [comment]
@pyros2097 
Based on the stack trace above I can tell that FuseBox has nothing to do with it. Please verify all the plugins and your code for errors. If nothing helps and you are confident that something is off, please create a repository where we could take a look at the issue and reproduce it.

**Comment by pyros2097** [comment]
Reproduced it in the react-example project.
Here.
https://github.com/pyros2097/react-example/blob/master/fuse.js

This is where I'm actually using it.
https://github.com/pyros2097/cress/blob/master/packages/cress-cli/bin/cress-build

This works in webpack in my other project,
https://github.com/pyros2097/web-boilerplate/blob/master/.babelrc

**Comment by nchanged** [comment]
Right you are using typescript and babel at the same time, if you noticed that example didn’t have any babel. Remove “useTypescripCompiler” option

**Comment by pyros2097** [comment]
Yeah. I've set it to false. You mean I should remove the field itself. Done. But still the same thing. Yeah I modified that example to use babel. It works fine with babel-preset-env. But fails with babel-preset-expo though. Thats what I'm facing now.
https://github.com/pyros2097/react-example/blob/master/fuse.js#L25

**Comment by nchanged** [comment]
It has something to do with JSX, FuseBox just pipes it to babel, everything else is up to the user. Maybe WebPack adds some extra plugins there? Idk,

And then the other thing, you need to convert imports to `require`otherwise it won't work.

**Comment by nchanged** [comment]
Closing this for now, feel free to re-open.
