### ISSUE TITLE
Quantum plugin crashes if undefined element is added to the plugin list

### ISSUE THREAD

**Issue by RPDeshaies** [fuse-box/fuse-box#939]
In the Fusebox doc, we see a lot of stuff that does

```
plugin: [
  aBoolean && SomePlugin(),
  anotherBoolean && AnotherPlugin(),
]
```

So if the condition if false, an undefined element is added to the plugin list instead of the plugin

It works fine with Fusebox, but when using the Quantum plugin, Quantum crashes as it seems as it's trying to bootstrap a undefined plugin

```
TypeError: Cannot read property 'constructor' of undefined
    at plugins.forEach (node_modules/fuse-box/quantum/plugin/QuantumPlugin.js:15:28)
    at Array.forEach (<anonymous>)
    at context.bundle.producer.bundles.forEach.bundle (node_modules/fuse-box/quantum/plugin/QuantumPlugin.js:14:21)
    at Map.forEach (<anonymous>)
    at QuantumPluginClass.init (node_modules/fuse-box/quantum/plugin/QuantumPlugin.js:12:41)
    at plugins.forEach.plugin (node_modules/fuse-box/core/WorkflowContext.js:410:34)
    at Array.forEach (<anonymous>)
    at WorkFlowContext.triggerPluginsMethodOnce (node_modules/fuse-box/core/WorkflowContext.js:395:22)
    at ModuleCollection.initPlugins (node_modules/fuse-box/core/ModuleCollection.js:51:22)
    at ModuleCollection.collectBundle (node_modules/fuse-box/core/ModuleCollection.js:71:14)
```

**Comment by RPDeshaies** [comment]
Quantum works if I use `_.compact()` on the plugin array
