### ISSUE TITLE
FuseBox.import does not exist

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#941]
I'm on fusebox `2.5.0-beta.1`.
I want to use wildcard imports. Unfortunately, `FuseBox.import` is not a function.

Usage:

```
const { FuseBox } = require('fuse-box');

FuseBox.import('./scripts/main/react/**/package.json');
```

```TypeError: FuseBox.import is not a function
    at SparkTask.Sparky.task [as fn] (/Users/.../src/ml-webclient/fuse.js:71:19)
    at Promise.all.then (/Users/.../src/ml-webclient/node_modules/fuse-box/dist/commonjs/sparky/Sparky.js:54:38)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3```

**Comment by nchanged** [comment]
@misantronic you shouldn't import fuse-box in your app.` fuse-box` is a package is used ONLY for bundling, not for requiring in your app.
FuseBox variable, however, is available in your app globally.
Remove the import statement 
```
FuseBox.import('./scripts/main/react/**/package.json');
```
