### ISSUE TITLE
UglifyJSPlugin in combination with CSSResourcePlugin throws

### ISSUE THREAD

**Issue by KnisterPeter** [fuse-box/fuse-box#954]
I try to bundle a lib we have here for use in a browser.
This works fine but when I try to create a production ready version it fails during minifying code using the UglifyJSPlugin.

I removed all the plugins we used step by step and it fails when the CSSResourcePlugin is in the config.

```sh
SyntaxError: Unexpected token: punc (.)
    at JS_Parse_Error.get (eval at <anonymous> (/home/marwol/src/ml-webclient-styleguide/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at Arithmetic_1.Arithmetic.getFiles.then.then.catch.e (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/dist/commonjs/core/FuseBox.js:357:26)
```

Any idea?

**Comment by nchanged** [comment]
@KnisterPeter hi
Yes, i have an idea. That means that your code contains es6 syntax. 

You have 2 options:

1) with Quantum: Upgrade the very latest `3.0.0-next.25` and install `uglify-es` and of course, make sure you have the latest `uglify-js`
2) Without Quantum and version `2.5` still install `uglify-es` and use it

**Comment by KnisterPeter** [comment]
@nchanged 
Thanks for your hints but unfortunately with `3.0.0-next.25` and `uglify-es` it still fails with this error:

```

Launching quantum core
  → Generating abstraction, this may take a while
SyntaxError: Unexpected token (38488:0)
    at Parser.pp$4.raise (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:2649:13)
    at Parser.pp.unexpected (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:637:8)
    at Parser.pp$3.parseExprAtom (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:2117:10)
    at Parser.parseExprAtom (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn-jsx/inject.js:397:24)
    at Parser.pp$3.parseExprSubscripts (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:1968:19)
    at Parser.pp$3.parseMaybeUnary (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:1945:17)
    at Parser.pp$3.parseExprOps (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:1887:19)
    at Parser.pp$3.parseMaybeConditional (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:1870:19)
    at Parser.pp$3.parseMaybeAssign (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:1845:19)
    at Parser.pp$3.parseExpression (/home/marwol/src/ml-webclient-styleguide/node_modules/fuse-box/node_modules/acorn/dist/acorn.js:1816:19)
```

**Comment by nchanged** [comment]
@KnisterPeter your config please?

**Comment by KnisterPeter** [comment]
Ouch, sorry. Bundled with webpack now. I'll try to recreate a simple example when I find a bit free time.

**Comment by nchanged** [comment]
Ok the feel free to reopen it
