### ISSUE TITLE
Test runner - throws ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by jezikk** [fuse-box/fuse-box#959]
Hi,

can you help me please. I have a project that works great with fuse-box:

https://github.com/jezikk/fuse-box-foundation-starter

`npm start dev` and `npm start build` commands work without any issues. I would like to create some test scenarios and if I tried to integrate test runner into my project using:
```
Sparky.task('test', ['clean', 'config'], () =>
    fuse.bundle('js/app').test('[**/**.test.ts]')
);
```
I get the following error:
```
ReferenceError: jQuery is not defined
    at Object.<anonymous> (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:10328:18)
    at __webpack_require__ (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:10275:30)
    at Object.<anonymous> (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:14759:65)
    at __webpack_require__ (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:10275:30)
    at Object.<anonymous> (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:22039:18)
    at __webpack_require__ (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:10275:30)
    at module.exports (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:10321:18)
    at d (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:10324:10)
    at Object.<anonymous> (C:\Users\Michal\Documents\Projects\fusebox-foundation-starter\.fusebox\tests\1511804963784\test.js:26154:1)
    at Module._compile (module.js:624:30)
```

I don't know where is a problem, as I said, the project in dev mode works without any problem. This is my fuse.js file:
```
const {
    FuseBox,
    Sparky,
    SassPlugin,
    CSSPlugin,
    CSSResourcePlugin,
    PostCSSPlugin,
    QuantumPlugin
} = require('fuse-box');

let fuse, isProduction;
isProduction = false;

const sassPaths = [
    'node_modules/foundation-sites/scss',
    'node_modules/font-awesome/scss',
    'node_modules/motion-ui/src'
];

const homedirPath = 'src';
const outputPath = 'dist/';
const devServerPath = './';

Sparky.task('config', () => {
    fuse = FuseBox.init({
        homeDir: homedirPath,
        output: `${outputPath}$name.js`,
        sourceMaps: !isProduction,
        cache: !isProduction,
        tsConfig: './tsconfig.json',
        plugins: [
            [
                SassPlugin({
                    includePaths: sassPaths,
                    outputStyle: 'compressed',
                    importer: true
                }),
                CSSResourcePlugin({
                    dist: 'dist/resources',
                    resolve: f => `/dist/resources/${f}`
                }),
                PostCSSPlugin([
                    require('autoprefixer')({
                        browsers: [
                            'last 2 versions',
                            'ie >= 9',
                            'and_chr >= 2.3'
                        ]
                    })
                ]),
                CSSPlugin({
                    outFile: f => `dist/${f}`,
                    inject: false
                })
            ],
            isProduction &&
                QuantumPlugin({
                    treeshake: true,
                    uglify: true,
                    bakeApiIntoBundle: 'js/app',
                    containedAPI: true
                })
        ],
        shim: {
            jquery: {
                source: 'node_modules/jquery/dist/jquery.js',
                exports: '$'
            },
            foundation: {
                source: 'node_modules/foundation-sites/dist/js/foundation.js',
                exports: 'Foundation'
            }
        }
    });
});

Sparky.task('clean', () => {
    return Sparky.src('dist/').clean('dist/');
});

Sparky.task('set-production-env', () => (isProduction = true));

Sparky.task('dev', ['clean', 'config'], () => {
    fuse.dev({
        root: devServerPath,
        httpServer: true,
        hmr: true,
        port: 3000
    });

    fuse
        .bundle('js/app')
        .watch()
        .hmr({ reload: true })
        .instructions('> js/index.ts');

    fuse.run();
});

Sparky.task('build', ['clean', 'set-production-env', 'config'], () => {
    fuse.bundle('js/app').instructions('> js/index.ts');
    fuse.run();
});

Sparky.task('test', ['clean', 'config'], () =>
    fuse.bundle('js/app').test('[**/**.test.ts]')
);
```

**Comment by devmondo** [comment]
jquery is a client-side only lib and not available on the server.

**Comment by jezikk** [comment]
Yes, It's true. Thanks.
