### ISSUE TITLE
UglifyESPlugin: screw_ie8 is an invalid option

### ISSUE THREAD

**Issue by nahuel** [fuse-box/fuse-box#988]
Create a project:

```shell
mkdir /tmp/t ; cd /tmp/t
npm init -y
npm install -D fuse-box uglify-es 
```

with this `fuse.js`:

```js
const { FuseBox, UglifyESPlugin } = require("fuse-box");

const fuse = FuseBox.init({
    homeDir: "src",         
    output: "dist/$name.js",
    plugins : [ UglifyESPlugin({ mangle : { toplevel : true ,
                                            screw_ie8 : true
                                          }})]
});

fuse.bundle("app")
    .instructions(`>xx.ts`); 

fuse.run();
```

Then run fusebox:

```
$ node fuse.js 
--- FuseBox 2.5.0-beta.1 ---

--------------------------
Bundle "app" 

└──  (0 files,  89 Bytes) default
size: 89 Bytes in 20ms
TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:479:11)
    at UglifyESPluginClass.postBundle (/tmp/t/node_modules/fuse-box/dist/commonjs/plugins/UglifyESPlugin.js:26:28)
    at plugins.forEach.plugin (/tmp/t/node_modules/fuse-box/dist/commonjs/core/WorkflowContext.js:480:34)
    at Array.forEach (<anonymous>)
    at WorkFlowContext.triggerPluginsMethodOnce (/tmp/t/node_modules/fuse-box/dist/commonjs/core/WorkflowContext.js:465:22)
    at FuseBox.triggerPost (/tmp/t/node_modules/fuse-box/dist/commonjs/core/FuseBox.js:160:22)
    at realm_utils_1.chain.then.then.result (/tmp/t/node_modules/fuse-box/dist/commonjs/core/FuseBox.js:293:26)
    at <anonymous>
```

If you remove the `screw_ie8` option, the bundling finishes ok. The `UglifyESPlugin` documentation is wrong, `screw_ie8` stopped being a valid option in the current `uglify-es` API.

**Comment by nchanged** [comment]
@nahuel could you fix up and make a PR? Any help is greatly appreciated!

**Comment by nchanged** [comment]
Closed due to inactivity
